### ISSUE TITLE
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'merge_pooled_embeddings'

### ISSUE THREAD

**Issue by mreso** [meta-pytorch/torchrec#1056]
Hi,

I am running into the following AttributeError in fbgemm_gpu when using TorchRec:

```
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'merge_pooled_embeddings'
```

Its called [here](https://github.com/pytorch/torchrec/blob/ec85e941de8c7dea65f427d514542241e3d48556/torchrec/distributed/dist_data.py#LL688C13-L688C53).

I see the issue in the current release 0.3.2 as well as the current nightlies.

Docker repro:
```Dockerfile
FROM nvidia/cuda:11.7.1-devel-ubuntu22.04

RUN apt-get -y update && apt-get install -y python3-pip
RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu117
RUN pip3 install fbgemm_gpu_nightly
RUN python3 -c "import torch; import fbgemm_gpu; print(torch.ops.fbgemm.merge_pooled_embeddings)"
```

Running "docker build ." fails with:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 562, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator fbgemm::merge_pooled_embeddings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 566, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'merge_pooled_embeddings'
```
This runs successful with TorchRec/fbgemm_gpu 0.2.0. Other ops like jagged_2d_to_dense are found. Was the op removed?

Thanks!

**Comment by mreso** [comment]
Closing here, better suited in fbgemm repo
