### ISSUE TITLE
Error in the dlrm example

### ISSUE THREAD

**Issue by shgoyal33** [meta-pytorch/torchrec#1221]
I was trying to follow the basic example mentioned in this page: [dlrm_example]( https://pytorch.org/torchrec/torchrec.models.html#module-torchrec.models.dlrm) . 

Since I don't have access to the GPU I'm using a CPU installation of torchrec which I installed using:

pip install torchrec
pip uninstall fbgemm-gpu -y
pip install fbgemm-gpu-cpu

The exact code I'm using is:

```
B = 2
D = 8

eb1_config = EmbeddingBagConfig(
   name="t1", embedding_dim=D, num_embeddings=100, feature_names=["f1", "f3"]
)
eb2_config = EmbeddingBagConfig(
   name="t2",
   embedding_dim=D,
   num_embeddings=100,
   feature_names=["f2"],
)

ebc = EmbeddingBagCollection(tables=[eb1_config, eb2_config])
model = DLRM(
   embedding_bag_collection=ebc,
   dense_in_features=100,
   dense_arch_layer_sizes=[20,8],
   over_arch_layer_sizes=[5, 1],
)

features = torch.rand((B, 100))

sparse_features = KeyedJaggedTensor.from_offsets_sync(
   keys=["f1", "f3"],
   values=torch.tensor([1, 2, 4, 5, 4, 3, 2, 9]),
   offsets=torch.tensor([0, 2, 4, 6, 8]),
)

logits = model(
   dense_features=features,
   sparse_features=sparse_features,
)
```

When I run this code I'm getting the following error:

Traceback (most recent call last):
  File "torch_recc.py", line 44, in <module>
    logits = model(
  File "/wrk/xhdhdnobkup5/sagargoy/anaconda3/envs/torch_rec/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/wrk/xhdhdnobkup5/sagargoy/anaconda3/envs/torch_rec/lib/python3.8/site-packages/torchrec/models/dlrm.py", line 573, in forward
    embedded_sparse = self.sparse_arch(sparse_features)
  File "/wrk/xhdhdnobkup5/sagargoy/anaconda3/envs/torch_rec/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/wrk/xhdhdnobkup5/sagargoy/anaconda3/envs/torch_rec/lib/python3.8/site-packages/torchrec/models/dlrm.py", line 99, in forward
    sparse_features: KeyedTensor = self.embedding_bag_collection(features)
  File "/wrk/xhdhdnobkup5/sagargoy/anaconda3/envs/torch_rec/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/wrk/xhdhdnobkup5/sagargoy/anaconda3/envs/torch_rec/lib/python3.8/site-packages/torchrec/modules/embedding_modules.py", line 185, in forward
    f = feature_dict[feature_name]
KeyError: 'f2'

How do I resolve this?

**Comment by henrylhtsang** [comment]
Looks like its another example of the website not up to date. The example has a few bugs. Refer to the unit test below for an implementation that runs.

https://github.com/pytorch/torchrec/blob/7bf0e6d98cb8b736e0807dc298488fb24791ed97/torchrec/models/tests/test_dlrm.py#L1177

**Comment by shgoyal33** [comment]
@henrylhtsang Hi Thank you so much for this. My end goal here is to get an onnx for analysis. When I try to save the onnx using torch.onnx.export method it throws an error: RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: KeyedJaggedTensor
Do you know how to export models from torchrec to onnx?

**Comment by henrylhtsang** [comment]
@shgoyal33 Hi looks like currently onnx doesn't support KeyedJaggedTensor as inputs. This seems like it could be a feature request to the onnx github.
