### ISSUE TITLE
How bad is it to work on CPU for torchrec?

### ISSUE THREAD

**Issue by roberthobblebottom** [meta-pytorch/torchrec#124]
I am a student working in a project making a MVP that will need to use a recommender system. Unfortunately I personally do not have a Nvidia GPU and im running on my Thinkpad T495s. 

How bad is it to work on CPU? I image I will need to use smaller datasets.

If not I may try out the free trails by Google or AWS

edit: My Computer specs:

![image](https://user-images.githubusercontent.com/60025340/156372888-f0ce0eae-aab8-4243-84a9-f2e82e70d358.png)

**Comment by roberthobblebottom** [comment]
I am getting this issue while trying out torchrec cpu,
```
(recommender) ryan@ryan-ThinkPad-T495s:~/Documents/is4103/is4103-capstone-id01/BackendML$ python3 recommender.py 
Traceback (most recent call last):
  File "/home/ryan/Documents/is4103/is4103-capstone-id01/BackendML/recommender.py", line 3, in <module>
    import torchrec
  File "/home/ryan/.local/lib/python3.9/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/home/ryan/.local/lib/python3.9/site-packages/torchrec/distributed/__init__.py", line 33, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/home/ryan/.local/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 16, in <module>
    from torch.distributed.fsdp import FullyShardedDataParallel
ModuleNotFoundError: No module named 'torch.distributed.fsdp'
```
It happened when I create a conda environment  and ran
 ```
conda install pytorch cpuonly -c pytorch-nightly
pip install torchrec-nightly-cpu
```

**Comment by s4ayub** [comment]
@themissingCRAM  

> How bad is it to work on CPU?

What do you mean by "bad" exactly? QPS?

Also, the cpu-only version installation process works on the colab environment  (along with the gpu version) and our own local environment (tried with python3.7 and python3.9).  Colab: https://colab.research.google.com/github/pytorch/torchrec/blob/main/Torchrec_Introduction.ipynb. You can create a copy of this tutorial and swap the `!pip3 install torchrec-nightly` command with `pip install torchrec-nightly-cpu` if you'd like to use the cpu only version. 

I did run into this issue when pytorch wasn't installed properly though. Are you sure that this command succeeded and installed pytorch correctly?

> conda install pytorch cpuonly -c pytorch-nightly

**Comment by s4ayub** [comment]
Closing due to inactivity.
