### ISSUE TITLE
why this simple piece of code running well on gpu but not working on cpu

### ISSUE THREAD

**Issue by Ye-Tian-Zero** [meta-pytorch/torchrec#1255]
``` python
import torch
import sys
import torchrec
import torch.distributed as dist
import os
from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
from torchrec.distributed.planner.types import ParameterConstraints
from torchrec.distributed.types import ShardingType
from torchrec.distributed.embedding import EmbeddingCollectionSharder
from typing import cast

os.environ["RANK"] = "0"
os.environ["WORLD_SIZE"] = "1"
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "29578"

def main(device_str):
    dist.init_process_group(backend='nccl' if device_str == 'cuda' else 'gloo')
    device = torch.device(device_str)
    ebc = torchrec.EmbeddingCollection(device='meta', tables=[
        torchrec.EmbeddingConfig(
            name="t1",
            embedding_dim=64,
            num_embeddings=10240,
            feature_names=["f1"],
        ),
        torchrec.EmbeddingConfig(
            name="t2",
            embedding_dim=64,
            num_embeddings=10240,
            feature_names=["f2"],
        ),
    ])

    topology = Topology(world_size=1, compute_device=device_str)

    planner = EmbeddingShardingPlanner(
        topology=topology,
        constraints={"t1":ParameterConstraints(
          sharding_types=[ShardingType.TABLE_WISE.value]),
                    "t2":ParameterConstraints(
          sharding_types=[ShardingType.TABLE_WISE.value])},
    )

    from torchrec.distributed.types import ModuleSharder, ShardingEnv
    sharders = [cast(ModuleSharder[torch.nn.Module], EmbeddingCollectionSharder())]

    plan = planner.collective_plan(ebc, sharders, dist.group.WORLD)

    sharded_model = torchrec.distributed.DistributedModelParallel(
            ebc,
            env=ShardingEnv.from_process_group(dist.group.WORLD),
            plan=plan,
            sharders=sharders,
            device=device,
        )


    mb = torchrec.KeyedJaggedTensor(
        keys = ["f1", "f2"],
        values = torch.tensor([101, 101, 202, 303, 404, 505, 606, 707]),
        lengths = torch.tensor([3, 1, 1, 1, 1, 1], dtype=torch.int64),
    ).to(device)

    print(sharded_model(mb)["f1"])

if __name__ == "__main__":
   main(sys.argv[1])
```

It works well when running `python test.py cuda`:

```
JaggedTensor({
    [[[0.0011029767338186502, -0.00395215954631567, -0.0018442791188135743, -0.007557584438472986, -0.0031797350384294987, 0.006282324902713299, -0.009845591150224209, -0.007376545574516058, 0.008753343485295773, -0.008200174197554588, 0.002929344307631254, -0.0033750245347619057, 0.0057535129599273205, -0.0007462849607691169, 0.0036815842613577843, -0.009199751541018486, 0.0038449959829449654, 0.0022021105978637934, 0.003057522000744939, 0.0053246840834617615, 0.009294470772147179, -0.006488552782684565, 0.0011513317003846169, -0.009052998386323452, 0.0030313024763017893, -0.0041050068102777, 0.00367907271720469, -0.003907319623976946, 0.00902373343706131, -0.009018014185130596, -0.0057495394721627235, 0.003596898401156068, -0.0030074671376496553, -0.009360070340335369, 0.008912479504942894, -0.00906705018132925, -0.005027097184211016, 0.0004475657478906214, 0.0012357241939753294, 0.006307156756520271, 0.005439601838588715, -0.0014856259804219007, 0.0041332426480948925, 0.007890472188591957, 0.00448508420959115, 0.0034024252090603113, -0.0025801125448197126, 0.006668792571872473, -0.0032300944440066814, 0.003970261663198471, -0.008858928456902504, 0.005157754756510258, -1.6807689462439157e-05, 0.005059598013758659, 0.0044680405408144, 0.0060621751472353935, -0.007198696956038475, -0.008796746842563152, -0.002840297296643257, -0.005909365601837635, -0.002690189750865102, -0.009595845825970173, 0.004992067813873291, 0.001254749484360218], [0.0011029767338186502, -0.00395215954631567, -0.0018442791188135743, -0.007557584438472986, -0.0031797350384294987, 0.006282324902713299, -0.009845591150224209, -0.007376545574516058, 0.008753343485295773, -0.008200174197554588, 0.002929344307631254, -0.0033750245347619057, 0.0057535129599273205, -0.0007462849607691169, 0.0036815842613577843, -0.009199751541018486, 0.0038449959829449654, 0.0022021105978637934, 0.003057522000744939, 0.0053246840834617615, 0.009294470772147179, -0.006488552782684565, 0.0011513317003846169, -0.009052998386323452, 0.0030313024763017893, -0.0041050068102777, 0.00367907271720469, -0.003907319623976946, 0.00902373343706131, -0.009018014185130596, -0.0057495394721627235, 0.003596898401156068, -0.0030074671376496553, -0.009360070340335369, 0.008912479504942894, -0.00906705018132925, -0.005027097184211016, 0.0004475657478906214, 0.0012357241939753294, 0.006307156756520271, 0.005439601838588715, -0.0014856259804219007, 0.0041332426480948925, 0.007890472188591957, 0.00448508420959115, 0.0034024252090603113, -0.0025801125448197126, 0.006668792571872473, -0.0032300944440066814, 0.003970261663198471, -0.008858928456902504, 0.005157754756510258, -1.6807689462439157e-05, 0.005059598013758659, 0.0044680405408144, 0.0060621751472353935, -0.007198696956038475, -0.008796746842563152, -0.002840297296643257, -0.005909365601837635, -0.002690189750865102, -0.009595845825970173, 0.004992067813873291, 0.001254749484360218], [0.0006042792811058462, -0.005009274929761887, -0.005214923992753029, 0.0028978753834962845, 0.0029007154516875744, -0.004149681888520718, -0.009372781030833721, 0.0022633203770965338, 0.002850278979167342, 0.009510575793683529, -0.001298762857913971, 0.003157828701660037, -0.009655014611780643, 0.0034504716750234365, 0.0046874904073774815, -0.003181858453899622, -0.0029968712478876114, -0.002313521457836032, -0.006302500609308481, -0.005781727842986584, -0.005920436233282089, 0.006518208421766758, 0.008258325047791004, 0.0063069164752960205, 0.008918942883610725, -0.0034651951864361763, 0.005910128820687532, 0.0002210639650002122, 0.007488134782761335, 0.0042960490100085735, 0.005291743669658899, 0.004527034237980843, 0.009509957395493984, 0.0027642231434583664, 0.004912311211228371, -1.3453808605845552e-05, -0.008500468917191029, -0.004629633855074644, -0.007502047810703516, 0.005495019257068634, 0.005550634581595659, 0.007346662692725658, -0.005841672420501709, -0.0021269251592457294, -0.008444245904684067, -0.0030279504135251045, -0.0007552350871264935, 0.007171630859375, -0.008134601637721062, 0.0077856373973190784, -0.0028599335346370935, -0.008516531437635422, 0.009663525968790054, -0.002887407783418894, -0.004317957442253828, 0.004561435431241989, -0.008505855686962605, -0.005239115096628666, 0.009392401203513145, 0.004260031506419182, -0.005170314107090235, 0.008997480385005474, -0.007190401665866375, -0.0011609456269070506]], [[0.009204263798892498, -0.0015473499661311507, -0.004784199874848127, -0.009188477881252766, -0.007183350156992674, 0.0030179470777511597, -0.0071774497628211975, -0.0052746357396245, 4.3082109186798334e-05, -0.004228099249303341, 0.004434850066900253, 0.001386576914228499, -0.004256696905940771, -0.009117458947002888, 0.009087726473808289, 0.008750530891120434, -0.0028224948327988386, 0.007001407444477081, 0.006137413904070854, -0.0028956993483006954, 0.007032893132418394, -0.003139166161417961, 0.0025796229019761086, -0.00036353437462821603, -0.003324655583128333, -0.0060738264583051205, -0.009226485155522823, 0.002967886161059141, 0.004603592678904533, -0.004162559751421213, 0.004448906518518925, 0.007625581696629524, 0.008486930280923843, 0.0013124216347932816, 0.005489327944815159, 0.003599703311920166, 0.00622149184346199, 0.009619040414690971, -0.007866822183132172, -0.006232406012713909, -0.005636227782815695, -0.0067508649080991745, -0.0042351530864834785, 0.006068134680390358, 0.007739453110843897, 0.001087466604076326, -0.0035874529276043177, 0.004434769973158836, 0.005455636419355869, -0.002446722472086549, 0.0027909823693335056, 0.004149329848587513, -0.0026118140667676926, 0.007289246190339327, -0.004930922295898199, -0.005246427375823259, -0.008656715042889118, -0.009332285262644291, 0.0026465144474059343, 0.00234101340174675, 4.429549153428525e-05, -0.009518904611468315, 0.0014536179369315505, 0.004660517908632755]], [[0.006071023177355528, 0.00481199286878109, -0.004291770979762077, -0.006864115130156279, 0.005353245884180069, -0.005868161097168922, -0.00524919806048274, 0.00421167304739356, -0.009875600226223469, -0.009314967319369316, -0.0008276451262645423, -0.007049708627164364, 0.007997059263288975, 0.004729739390313625, 0.009451654739677906, -0.004006832838058472, -0.004795784130692482, 0.00901763141155243, 0.005168118979781866, 0.007638545706868172, 0.0020765268709510565, 0.006543322931975126, 0.005143120884895325, -0.00395594909787178, -0.006001586094498634, -0.006223458331078291, 0.002831354970112443, 0.004091653972864151, 0.0013473128201439977, -0.009696592576801777, 0.008726825006306171, -0.003398686181753874, 0.0009426972246728837, -0.007748925127089024, -0.004417194984853268, -0.005182633176445961, -0.0011516927042976022, -0.0054591805674135685, 0.004459850490093231, 0.00010345666669309139, 0.007801137864589691, -0.0004345177731011063, -0.006344292778521776, -0.009615271352231503, 0.0038973987102508545, 0.0024506687186658382, -0.007428143639117479, 0.0036031585186719894, 0.008356848731637001, 0.0008825747645460069, -0.007460119668394327, 0.008402864448726177, -0.007269291207194328, 0.009563140571117401, -0.0009295061463490129, -0.0026973308995366096, 0.002174010733142495, 0.00190873967949301, 0.001536006573587656, -0.0038946475833654404, -0.0008524752338416874, -0.006493027321994305, 0.0015359052922576666, 0.00734842149540782]]]
})
```

But failed when running `python test.py cpu`:
```
Traceback (most recent call last):
  File "test.py", line 68, in <module>
    main(sys.argv[1])
  File "test.py", line 65, in main
    print(sharded_model(mb)["f1"])
  File "/usr/local/lib/python3.8/dist-packages/torchrec/distributed/types.py", line 365, in impl
    LazyAwaitable._wait_async(lhs), LazyAwaitable._wait_async(rhs)
  File "/usr/local/lib/python3.8/dist-packages/torchrec/distributed/types.py", line 298, in _wait_async
    obj._result = obj.wait()
  File "/usr/local/lib/python3.8/dist-packages/torchrec/distributed/types.py", line 222, in wait
    ret: W = self._wait_impl()
  File "/usr/local/lib/python3.8/dist-packages/torchrec/distributed/embedding.py", line 274, in _wait_impl
    _construct_jagged_tensors(
  File "/usr/local/lib/python3.8/dist-packages/torchrec/distributed/embedding.py", line 211, in _construct_jagged_tensors
    embeddings_list = torch.split(embeddings, length_per_key, dim=0)
  File "/usr/local/lib/python3.8/dist-packages/torch/functional.py", line 189, in split
    return tensor.split(split_size_or_sections, dim)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 803, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 6 (input tensor's size at dimension 0), but got split_sizes=[5, 3]
```

**Comment by henrylhtsang** [comment]
looking into it

**Comment by henrylhtsang** [comment]
Hi @Ye-Tian-Zero, so apparently this is a fbgemm problem. What they told us is that they don't support Pooling type None (e.g. when we are using EmbeddingCollection) for device cpu yet. I will ask if they plan on changing that.


Repro as follows:
```
import torch
from fbgemm_gpu.split_table_batched_embeddings_ops import (
    ComputeDevice,
    EmbeddingLocation,
    PoolingMode,
    SplitTableBatchedEmbeddingBagsCodegen,
)
from torchrec.distributed.embedding_types import (
    compute_kernel_to_embedding_location,
    EmbeddingComputeKernel,
)
from torchrec.sparse.jagged_tensor import KeyedJaggedTensor

# cuda 
local_rows = [10240, 10240]
local_cols = [64, 64]
managed = [compute_kernel_to_embedding_location(EmbeddingComputeKernel.FUSED)] * 2
compute_devices = [ComputeDevice.CUDA] * 2
feature_table_map = [0, 1]
device = torch.device("cuda")

emb_module = SplitTableBatchedEmbeddingBagsCodegen(
    embedding_specs=list(
        zip(local_rows, local_cols, managed, compute_devices)
    ),
    feature_table_map=feature_table_map,
    pooling_mode=PoolingMode.NONE,
    # weights_precision=weights_precision,
    device=device,
)

mb = KeyedJaggedTensor(
    keys = ["f1", "f2"],
    values = torch.tensor([101, 101, 202, 303, 404, 505, 606, 707]),
    lengths = torch.tensor([3, 1, 1, 1, 1, 1], dtype=torch.int64),
).to(device)

print(emb_module(indices=mb.values().long(), offsets=mb.offsets().long()).shape)

# cpu
local_rows = [10240, 10240]
local_cols = [64, 64]
managed = [EmbeddingLocation.HOST] * 2
compute_devices = [ComputeDevice.CPU] * 2
feature_table_map = [0, 1]
device = torch.device("cpu")

emb_module = SplitTableBatchedEmbeddingBagsCodegen(
    embedding_specs=list(
        zip(local_rows, local_cols, managed, compute_devices)
    ),
    feature_table_map=feature_table_map,
    pooling_mode=PoolingMode.NONE,
    # weights_precision=weights_precision,
    device=device,
)

mb = KeyedJaggedTensor(
    keys = ["f1", "f2"],
    values = torch.tensor([101, 101, 202, 303, 404, 505, 606, 707]),
    lengths = torch.tensor([3, 1, 1, 1, 1, 1], dtype=torch.int64),
).to(device)

print(emb_module(indices=mb.values().long(), offsets=mb.offsets().long()).shape)
```

**Comment by Ye-Tian-Zero** [comment]
Got it, thanks for your response! 😆

**Comment by henrylhtsang** [comment]
@Ye-Tian-Zero Update: FBGEMM has no plan to support Pooling type None for cpu for now.

**Comment by Ye-Tian-Zero** [comment]
Sure, thank you! Just for me, I mostly use cuda now. So I would close this issue now.
