### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by BackNode** [meta-pytorch/torchrec#143]
Hi all,

I am trying to run a simple model based on TorchRec, while ``DistributedModelParallel`` instance ``model.named_parameters()`` returns empty parameter list. Could you please help take a look?

ValueError: optimizer got an empty parameter list

model debug info and exception message:
```
model:  DistributedModelParallel(
  (_dmp_wrapped_module): CFTorchRecModelTrain(
    (model): CFTorchRecModel(
      (user_embedding): ShardedEmbeddingCollection(
        (_input_dists): ModuleList()
        (_lookups): ModuleList(
          (0): GroupedEmbeddingsLookup(
            (_emb_modules): ModuleList(
              (0): BatchedFusedEmbedding(
                (_emb_module): SplitTableBatchedEmbeddingBagsCodegen()
              )
            )
          )
        )
        (_output_dists): ModuleList(
          (0): RwSequenceEmbeddingDist(
            (_dist): SequenceEmbeddingAllToAll()
          )
        )
      )
      (item_embedding): ShardedEmbeddingCollection(
        (_input_dists): ModuleList()
        (_lookups): ModuleList(
          (0): GroupedEmbeddingsLookup(
            (_emb_modules): ModuleList(
              (0): BatchedFusedEmbedding(
                (_emb_module): SplitTableBatchedEmbeddingBagsCodegen()
              )
            )
          )
        )
        (_output_dists): ModuleList(
          (0): RwSequenceEmbeddingDist(
            (_dist): SequenceEmbeddingAllToAll()
          )
        )
      )
      (cos): CosineSimilarity()
    )
  )
)

model.plan:  {'model.user_embedding': {'t_users': ParameterSharding(sharding_type='row_wise', compute_kernel='batched_fused', ranks=[0], sharding_spec=EnumerableShardingSpec(shards=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[7000000, 32], placement=rank:0/cuda:0)]))}, 'model.item_embedding': {'t_items': ParameterSharding(sharding_type='row_wise', compute_kernel='batched_fused', ranks=[0], sharding_spec=EnumerableShardingSpec(shards=[ShardMetadata(shard_offsets=[0, 0], shard_sizes=[32941588, 32], placement=rank:0/cuda:0)]))}}

dict: model.named_parameters():  {}

Traceback (most recent call last):
  File "/vc_data/users/GitSource/deeprank/collaborative_filtering/src/main_torchrec.py", line 284, in <module>
    main()
  File "/vc_data/users/GitSource/deeprank/collaborative_filtering/src/main_torchrec.py", line 184, in main
    optimizer = KeyedOptimizerWrapper(
  File "/vc_data/users/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/optim/keyed.py", line 339, in __init__
    self._optimizer: optim.Optimizer = optim_factory(list(params.values()))
  File "/vc_data/users/GitSource/deeprank/collaborative_filtering/src/main_torchrec.py", line 186, in <lambda>
    lambda params: torch.optim.SGD(params, lr=args.learning_rate),
  File "/vc_data/users/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/optim/sgd.py", line 105, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/vc_data/users/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/optim/optimizer.py", line 49, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

Code Snippet
torchrec_model.py
```Python
class CFTorchRecModel(nn.Module):
    """model define"""
    def __init__(
        self,
        num_users: int,
        num_items: int,
        factors: int,
    ) -> None:
        super().__init__()
        user_eb_configs = [
            EmbeddingConfig(
                name="t_users",
                embedding_dim=factors,
                num_embeddings=num_users,
                feature_names=["users"],
            ),
        ]
        item_eb_configs = [
            EmbeddingConfig(
                name="t_items",
                embedding_dim=factors,
                num_embeddings=num_items,
                feature_names=["items"],
            )
        ]
        self.user_embedding: EmbeddingCollection = EmbeddingCollection(
            tables=user_eb_configs, device=torch.device("meta")
        )
        self.item_embedding: EmbeddingCollection = EmbeddingCollection(
            tables=item_eb_configs, device=torch.device("meta")
        )
        self.cos = nn.CosineSimilarity(dim=1, eps=1e-6)

    def forward(self, users: Tensor, items: Tensor) -> torch.Tensor:
        """forward"""
        user_features = KeyedJaggedTensor(
            keys=["users"],
            values=users.reshape(1, -1),
            offsets=torch.tensor([i for i in range(users.shape[0] + 1)]),
        )
        user_embs = self.user_embedding(user_features)["users"].values()

        item_features = KeyedJaggedTensor(
            keys=["items"],
            values=items.reshape(1, -1),
            offsets=torch.tensor([i for i in range(items.shape[0] + 1)]),
        )
        item_embs = self.item_embedding(item_features)["items"].values()

        scores = torch.sum(user_embs * item_embs, dim=1)
        return nn.sigmod(scores)

    def bpr_loss(self, users: Tensor, pos: Tensor, neg: Tensor, cosine_loss_multiplier: float):
        """bpr loss"""

        user_features = KeyedJaggedTensor(
            keys=["users"],
            values=users.reshape(1, -1),
            offsets=users.new_ones(users.shape[0] + 1).cumsum(0) - 1  # torch.tensor([i for i in range(users.shape[0] + 1)]),
        )
        user_embs: Tensor = self.user_embedding(user_features)["users"].values()

        pos_features = KeyedJaggedTensor(
            keys=["items"],
            values=pos.reshape(1, -1),
            offsets=users.new_ones(pos.shape[0] + 1).cumsum(0) - 1 # torch.tensor([i for i in range(pos.shape[0] + 1)]),
        )
        pos_embs: Tensor = self.item_embedding(pos_features)["items"].values()

        neg_features = KeyedJaggedTensor(
            keys=["items"],
            values=neg.reshape(1, -1),
            offsets=users.new_ones(neg.shape[0] + 1).cumsum(0) - 1 # torch.tensor([i for i in range(neg.shape[0] + 1)]),
        )
        neg_embs: Tensor = self.item_embedding(neg_features)["items"].values()
        pos_scores = self.cos(user_embs, pos_embs)
        neg_scores = self.cos(user_embs, neg_embs)
        loss = torch.mean(nn.functional.softplus(cosine_loss_multiplier * (neg_scores - pos_scores)))
        return loss


class CFTorchRecModelTrain(nn.Module):
    """nn.Module to wrap CFTorchRecModel to use with train_pipeline."""
    def __init__(
        self,
        num_users: int,
        num_items: int,
        factors: int,
        cosine_loss_multiplier: float,
    ) -> None:
        super().__init__()
        self.model = CFTorchRecModel(num_users, num_items, factors)
        # self.model = BprMF(num_users, num_items, factors)
        self.cosine_loss_multiplier = cosine_loss_multiplier

    def forward(
        self, batch: Batch
    ) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
        """forward, compute loss"""
        loss = self.model.bpr_loss(batch.users, batch.pos_items, batch.neg_items, self.cosine_loss_multiplier)

        return loss, (loss.detach(), batch.users.detach())
```

main.py
```Python
    train_model = CFTorchRecModelTrain(num_users, num_items, args.factors, args.cosine_loss_multiplier)

    # sharders and planner
    sharding_types = [
        ShardingType.DATA_PARALLEL.value,
        # ShardingType.TABLE_WISE.value,
        ShardingType.ROW_WISE.value,
    ]
    constraints = {
            "t_users": ParameterConstraints(sharding_types=sharding_types),
            "t_items": ParameterConstraints(sharding_types=sharding_types),
        }

    sharders = [EmbeddingCollectionSharder()]
    pg = dist.GroupMember.WORLD
    assert pg is not None, "Process group is not initialized"
    env = ShardingEnv.from_process_group(pg)
    planner = EmbeddingShardingPlanner(
        topology=Topology(
            world_size=env.world_size, compute_device=device.type,
        ),
        constraints=constraints,
    )
    if pg is not None:
        plan = planner.collective_plan(train_model, sharders, pg)
    else:
        plan = planner.plan(train_model, sharders)

    model = DistributedModelParallel(
        module=train_model,
        sharders=sharders,
        plan=plan,
        env=env,
        device=device,
    )
    print("model: ", model)
    print("model.plan: ", model.plan)
    # print("model.named_children(): ", dict(model.named_children()))
    print("dict: model.named_parameters(): ", dict(model.named_parameters()))
    optimizer = KeyedOptimizerWrapper(
        dict(model.named_parameters()),
        lambda params: torch.optim.SGD(params, lr=args.learning_rate),
    )
```

**Comment by colin2328** [comment]
Hi @BackNode 
it looks like you are trying to run this on a single GPU, is that correct?

Can you add more details (including import statements and the values for   ( num_users, num_items, args.factors, args.cosine_loss_multiplier)

**Comment by BackNode** [comment]
@colin2328 Yes, I am debugging this on a single GPU, same exception will be thrown on multi-GPUs.

num_users = 7000000, num_items = 30000000, args.factors = 32, args.cosine_loss_multiplier = 20

import statements in torchrec_model.py
```Python
from typing import Dict, Iterator, Tuple, Optional, List
import numpy as np

import torch
from torch import Tensor, long, nn
from torchrec_utils import Batch
from torch import distributed as dist
from torchrec.modules.embedding_modules import EmbeddingCollection
from torchrec.modules.embedding_configs import EmbeddingConfig
from torchrec.optim.keyed import KeyedOptimizerWrapper
from torchrec.sparse.jagged_tensor import (
    KeyedJaggedTensor,
    KeyedTensor,
)
```

import statements in main.py
```Python
import gc
import itertools
import os
import sys
from typing import Dict, Iterator, Tuple, Optional, List
import argparse
import numpy as np

import torch
from torch import Tensor, long, nn
from torch.utils.data import DataLoader
from tqdm import tqdm
from torch import distributed as dist
from torchrec.distributed import TrainPipelineSparseDist
from torchrec.distributed.model_parallel import DistributedModelParallel
from torchrec.distributed.embedding import EmbeddingCollectionSharder
from torchrec.optim.keyed import KeyedOptimizerWrapper

from torchrec_model import CFTorchRecModelTrain
from torchrec.distributed.types import (
    ShardingEnv,
    ShardingType,
)
from torchrec.distributed.planner import (
    EmbeddingShardingPlanner,
    ParameterConstraints,
    Topology,
)
```

**Comment by colin2328** [comment]
@BackNode  
A DistributedModelParallel module parameters (e.g parameter() or named_parameters ) will not give the shardedModule parameters when optimizer fusion is enabled. (We understand this is confusing and are working on the best way to clarify). In your case, since your entire module 's params are sharded and using optimizer fusion, named_parameters is returning None

Relatedly, we actually just fixed a bug in the example dlrm model (perhaps where your getting this example from) today - see https://github.com/pytorch/torchrec/pull/148/files . Here we're also getting the fused_optimizer from the DMP wrapped module.

Hopefully this helps

**Comment by BackNode** [comment]
Thank you @colin2328 . It works after I switch to ``model.fused_optimizer`` following the updated DLRM example.

BTW, it also works if I add constraints of sharding_types and compute_kernels.

```Python
    # sharders and planner
    sharding_types = [
        # ShardingType.DATA_PARALLEL.value,
        # ShardingType.TABLE_WISE.value,
        ShardingType.ROW_WISE.value,
    ]
    compute_kernels = [
        EmbeddingComputeKernel.SPARSE.value,
    ]
    constraints = {
            "t_users": ParameterConstraints(sharding_types=sharding_types, compute_kernels=compute_kernels),
            "t_items": ParameterConstraints(sharding_types=sharding_types, compute_kernels=compute_kernels),
        }

    sharders = [EmbeddingCollectionSharder()]
    pg = dist.GroupMember.WORLD
    assert pg is not None, "Process group is not initialized"
    env = ShardingEnv.from_process_group(pg)
    planner = EmbeddingShardingPlanner(
        topology=Topology(
            world_size=env.world_size, compute_device=device.type,
        ),
        constraints=constraints,
    )
    if pg is not None:
        plan = planner.collective_plan(train_model, sharders, pg)
    else:
        plan = planner.plan(train_model, sharders)

    model = DistributedModelParallel(
        module=train_model,
        sharders=sharders,
        plan=plan,
        env=env,
        device=device,
    )

    optimizer = KeyedOptimizerWrapper(
        dict(model.named_parameters()),
        lambda params: torch.optim.SGD(params, lr=args.learning_rate),
    )

    train_pipeline = TrainPipelineSparseDist(
        model,
        optimizer,
        device,
    )
```

**Comment by colin2328** [comment]
@BackNode  glad to hear that it worked.

it makes sense that ```         EmbeddingComputeKernel.SPARSE.value, ```
Will work (i.e parameters are included in parameters()), since it's not a fused kernel.

closing this task, feel free to re-open/re-create if there is another issue
