### ISSUE TITLE
Has anyone been able to run torchrec on Mac OS?

### ISSUE THREAD

**Issue by justin8shan** [meta-pytorch/torchrec#1609]
I am not able to install FBGEMM package on macOS with Intel chip. Any advice?

**Comment by gnahzg** [comment]
Can you provide the error message so we could take a look at?

Another source, https://github.com/pytorch/FBGEMM you can go here and get more instruction on FBGEMM.

**Comment by justin8shan** [comment]
Yes. To be specific, I was trying to install fbgemm-gpu on Mac. Below is the error I got

```
(torchrec) ➜  torchrec git:(main) ✗ pip install pip install fbgemm-gpu --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
Requirement already satisfied: pip in /Users/xshan/miniconda3/envs/torchrec/lib/python3.10/site-packages (23.3.1)
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install
```
MasOS: Ventura
Processor: Intel Core i7

**Comment by justin8shan** [comment]
If I follow the instructions on https://pytorch.org/FBGEMM/general/BuildInstructions.html#fbgemm-gpu-docs-build-setup-tools-install to build CPU only with below command.
```
(torchrec) ➜  fbgemm_gpu git:(main) ✗ python setup.py bdist_wheel \
    --package_name="${package_name}" \
    --package_variant=cpu \
    --python-tag="${python_tag}" \
    --plat-name="-13.6-${ARCH}"
```
I got CMake error
```
Not searching for unused variables given on the command line.
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File "/Users/xshan/miniconda3/envs/torchrec/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
    env = cmkr.configure(
  File "/Users/xshan/miniconda3/envs/torchrec/lib/python3.10/site-packages/skbuild/cmaker.py", line 357, in configure
    raise SKBuildError(msg)
```

**Comment by henrylhtsang** [comment]
Hi, 

Seems like this issue is about installing FBGEMM on Mac os. I suggest asking in https://github.com/pytorch/FBGEMM

**Comment by justin8shan** [comment]
sure will do. Has anyone tried to install torchRec Successfully on MacOS?

**Comment by justin8shan** [comment]
move issue to fbgemm repo

**Comment by wlrd** [comment]
@justin8shan did you ever get this sorted out? Running into the same issue now.

**Comment by kauabh** [comment]
any ideas around this
