### ISSUE TITLE
Error when testing installation of torchec

### ISSUE THREAD

**Issue by justin8shan** [meta-pytorch/torchrec#1611]
After installing torchrec, having trouble to run test installation (`torchx run -s local_cwd dist.ddp -j 1x2 --gpu 2 --script test_installation.py`) successfully. Can someone advise?

package version: 
torch                         2.1.0
torchaudio                    2.1.0
torchdata                     0.7.0
torchmetrics                  1.0.3
torchnet                      0.0.4
torchrec                      0.5.0
torchtext                     0.16.0
torchvision                   0.16.0
torchx                        0.6.0

```
# torchx run -s local_cwd dist.ddp -j 1x2 --gpu 2 --script test_installation.py
torchx 2024-01-07 07:19:05 INFO     Tracker configurations: {}
torchx 2024-01-07 07:19:05 INFO     Log directory not set in scheduler cfg. Creating a temporary log dir that will be deleted on exit. To preserve log directory set the `log_dir` cfg option
torchx 2024-01-07 07:19:05 INFO     Log directory is: /tmp/torchx_mqru63i2
torchx 2024-01-07 07:19:05 WARNING  

======================================================================
Running multiple role replicas that require GPUs without
setting `CUDA_VISIBLE_DEVICES` may result in multiple
processes using the same GPU device with undesired consequences
such as CUDA OutOfMemory errors.

To have TorchX set `CUDA_VISIBLE_DEVICES` to divide the
available GPUs on this host equally among the role replicas
set the `auto_set_cuda_visible_devices = True` scheduler runopt
======================================================================
                            
local_cwd://torchx/test_installation-rk4111n9jff15c
torchx 2024-01-07 07:19:05 INFO     Waiting for the app to finish...
test_installation/0 [2024-01-07 07:19:07,384] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
test_installation/0 [2024-01-07 07:19:07,384] torch.distributed.run: [WARNING] 
test_installation/0 [2024-01-07 07:19:07,384] torch.distributed.run: [WARNING] *****************************************
test_installation/0 [2024-01-07 07:19:07,384] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
test_installation/0 [2024-01-07 07:19:07,384] torch.distributed.run: [WARNING] *****************************************
test_installation/0 [0]:Traceback (most recent call last):
test_installation/0 [0]:  File "/root/gitrepo/torchrec/test_installation.py", line 16, in <module>
test_installation/0 [0]:    from torchrec import EmbeddingBagCollection, KeyedJaggedTensor
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/__init__.py", line 8, in <module>
test_installation/0 [0]:    import torchrec.distributed  # noqa
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/distributed/__init__.py", line 36, in <module>
test_installation/0 [0]:    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/distributed/model_parallel.py", line 24, in <module>
test_installation/0 [0]:    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/distributed/planner/__init__.py", line 22, in <module>
test_installation/0 [0]:    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/distributed/planner/planners.py", line 19, in <module>
test_installation/0 [0]:    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/distributed/planner/constants.py", line 10, in <module>
test_installation/0 [0]:    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/distributed/embedding_types.py", line 27, in <module>
test_installation/0 [0]:    from torchrec.modules.embedding_configs import (
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/modules/__init__.py", line 24, in <module>
test_installation/0 [0]:    from . import (  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/modules/embedding_modules.py", line 19, in <module>
test_installation/0 [1]:Traceback (most recent call last):
test_installation/0 [0]:    from torchrec.sparse.jagged_tensor import JaggedTensor, KeyedJaggedTensor, KeyedTensor
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/sparse/__init__.py", line 33, in <module>
test_installation/0 [0]:    from . import jagged_tensor  # noqa
test_installation/0 [1]:  File "/root/gitrepo/torchrec/test_installation.py", line 16, in <module>
test_installation/0 [1]:    from torchrec import EmbeddingBagCollection, KeyedJaggedTensor
test_installation/0 [0]:  File "/root/gitrepo/torchrec/torchrec/sparse/jagged_tensor.py", line 16, in <module>
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/__init__.py", line 8, in <module>
test_installation/0 [1]:    import torchrec.distributed  # noqa
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/distributed/__init__.py", line 36, in <module>
test_installation/0 [0]:    from torch.utils._pytree import register_pytree_node
test_installation/0 [1]:    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
test_installation/0 [0]:ImportError: cannot import name 'register_pytree_node' from 'torch.utils._pytree' (/opt/conda/lib/python3.10/site-packages/torch/utils/_pytree.py)
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/distributed/model_parallel.py", line 24, in <module>
test_installation/0 [1]:    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/distributed/planner/__init__.py", line 22, in <module>
test_installation/0 [1]:    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/distributed/planner/planners.py", line 19, in <module>
test_installation/0 [1]:    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/distributed/planner/constants.py", line 10, in <module>
test_installation/0 [1]:    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/distributed/embedding_types.py", line 27, in <module>
test_installation/0 [1]:    from torchrec.modules.embedding_configs import (
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/modules/__init__.py", line 24, in <module>
test_installation/0 [1]:    from . import (  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/modules/embedding_modules.py", line 19, in <module>
test_installation/0 [1]:    from torchrec.sparse.jagged_tensor import JaggedTensor, KeyedJaggedTensor, KeyedTensor
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/sparse/__init__.py", line 33, in <module>
test_installation/0 [1]:    from . import jagged_tensor  # noqa
test_installation/0 [1]:  File "/root/gitrepo/torchrec/torchrec/sparse/jagged_tensor.py", line 16, in <module>
test_installation/0 [1]:    from torch.utils._pytree import register_pytree_node
test_installation/0 [1]:ImportError: cannot import name 'register_pytree_node' from 'torch.utils._pytree' (/opt/conda/lib/python3.10/site-packages/torch/utils/_pytree.py)
test_installation/0 [2024-01-07 07:19:12,741] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 124) of binary: /opt/conda/bin/python
test_installation/0 Traceback (most recent call last):
test_installation/0   File "/opt/conda/bin/torchrun", line 33, in <module>
test_installation/0     sys.exit(load_entry_point('torch==2.1.0', 'console_scripts', 'torchrun')())
test_installation/0   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
test_installation/0     return f(*args, **kwargs)
test_installation/0   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
test_installation/0     run(args)
test_installation/0   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
test_installation/0     elastic_launch(
test_installation/0   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
test_installation/0     return launch_agent(self._config, self._entrypoint, list(args))
test_installation/0   File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
test_installation/0     raise ChildFailedError(
test_installation/0 torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
test_installation/0 ============================================================
test_installation/0 test_installation.py FAILED
test_installation/0 ------------------------------------------------------------
test_installation/0 Failures:
test_installation/0 [1]:
test_installation/0   time      : 2024-01-07_07:19:12
test_installation/0   host      : pytorch-2-1-0-gpu--ml-g4dn-2xlarge-dc76025e53dcd2e7c89481a0eb07
test_installation/0   rank      : 1 (local_rank: 1)
test_installation/0   exitcode  : 1 (pid: 125)
test_installation/0   error_file: <N/A>
test_installation/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
test_installation/0 ------------------------------------------------------------
test_installation/0 Root Cause (first observed failure):
test_installation/0 [0]:
test_installation/0   time      : 2024-01-07_07:19:12
test_installation/0   host      : pytorch-2-1-0-gpu--ml-g4dn-2xlarge-dc76025e53dcd2e7c89481a0eb07
test_installation/0   rank      : 0 (local_rank: 0)
test_installation/0   exitcode  : 1 (pid: 124)
test_installation/0   error_file: <N/A>
test_installation/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
test_installation/0 ============================================================
torchx 2024-01-07 07:19:13 INFO     Job finished: FAILED
torchx 2024-01-07 07:19:13 ERROR    AppStatus:
  msg: <NONE>
  num_restarts: 0
  roles: []
  state: FAILED (5)
  structured_error_msg: <NONE>
  ui_url: file:///tmp/torchx_mqru63i2/torchx/test_installation-rk4111n9jff15c
```

**Comment by henrylhtsang** [comment]
The error is `test_installation/0 [0]:ImportError: cannot import name 'register_pytree_node' from 'torch.utils._pytree' (/opt/conda/lib/python3.10/site-packages/torch/utils/_pytree.py)`

`test_installation/0 [1]:    from torch.utils._pytree import register_pytree_node` This line of code is recently changed, so it is not in torchrec 0.5.0. Are you sure you are not using torchrec nightly?

**Comment by justin8shan** [comment]
ok. my bad. I cloned the main branch of repo to local to run test installation. I am closing the issue now.
