### ISSUE TITLE
Multi-GPUs: Partial Ranks Hang for a long time after other ranks finished

### ISSUE THREAD

**Issue by BackNode** [meta-pytorch/torchrec#189]
Hi All,

I am running a multi-GPU job on a single node.  The job will always hang at final epoch. 3 out of 8 ranks will hang for a long time util time out and throw below exception. Looks like finished ranks just exit and release all the resource while the rest ranks are waiting for something. Any idea why?

```Bash
Epoch 9, Rank 7, world_size 8: 35batch [00:03, 10.54batch/s]
Epoch 9, Rank 2, world_size 8: 35batch [00:03, 10.54batch/s]
Epoch 9, Rank 5, world_size 8: 35batch [00:03, 10.51batch/s]
Epoch 9, Rank 0, world_size 8: 35batch [00:03, 10.53batch/s]
Epoch 9, Rank 3, world_size 8: 35batch [00:03, 10.47batch/s]
Epoch 9, Rank 6, world_size 8: 16batch [00:17, 11.32batch/s][E ProcessGroupNCCL.cpp:717] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4190, OpType=ALLTOALL_BASE, Timeout(ms)=1800000) ran for 1803657 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:717] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4188, OpType=ALLTOALL_BASE, Timeout(ms)=1800000) ran for 1803676 milliseconds before timing out.
Epoch 9, Rank 4, world_size 8: 26batch [30:06, 69.48s/batch]
Traceback (most recent call last):
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 300, in <module>
    main()
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 253, in main
    train(args, train_pipeline, train_dataloader, rank, world_size)
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 103, in train
    _train(train_pipeline, train_iterator, next_iterator, epoch, rank, world_size)
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 86, in _train
    train_pipeline.progress(combined_iterator)
  File "/GitSource/collaborative_filtering/src/torchrec_pipeline.py", line 69, in progress
    (losses, output) = cast(Tuple[torch.Tensor, Out], self._model(batch_i))
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 245, in forward
    return self._dmp_wrapped_module(*args, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GitSource/collaborative_filtering/src/torchrec_model.py", line 240, in forward
    loss = self.model.contrastive_loss(
  File "/GitSource/collaborative_filtering/src/torchrec_model.py", line 153, in contrastive_loss
    pos_items: Tensor = self.item_embedding(pos_features)["items"].values()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 415, in forward
    dist_input = self.input_dist(ctx, *input, **kwargs).wait()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/embedding.py", line 325, in input_dist
    tensor_awaitable = tensor_awaitable.wait()  # finish lengths all2all
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 117, in wait
    ret: W = self._wait_impl()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 112, in _wait_impl
    id_list_features_awaitable=self._id_list_features_awaitable.wait()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 117, in wait
    ret: W = self._wait_impl()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 384, in _wait_impl
    ret = KJTAllToAllIndicesAwaitable(
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 175, in __init__
    self._values_awaitable: dist.Work = dist.all_to_all_single(
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2612, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL communicator was aborted on rank 4.  Original reason for failure was: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4190, OpType=ALLTOALL_BASE, Timeout(ms)=1800000) ran for 1803657 milliseconds before timing out.
Epoch 9, Rank 1, world_size 8: 26batch [30:06, 69.49s/batch]
Traceback (most recent call last):
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 300, in <module>
    main()
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 253, in main
    train(args, train_pipeline, train_dataloader, rank, world_size)
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 103, in train
    _train(train_pipeline, train_iterator, next_iterator, epoch, rank, world_size)
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 86, in _train
    train_pipeline.progress(combined_iterator)
  File "/GitSource/collaborative_filtering/src/torchrec_pipeline.py", line 69, in progress
    (losses, output) = cast(Tuple[torch.Tensor, Out], self._model(batch_i))
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 245, in forward
    return self._dmp_wrapped_module(*args, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GitSource/collaborative_filtering/src/torchrec_model.py", line 240, in forward
    loss = self.model.contrastive_loss(
  File "/GitSource/collaborative_filtering/src/torchrec_model.py", line 152, in contrastive_loss
    users: Tensor = self.user_embedding(user_features)["users"].values()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 415, in forward
    dist_input = self.input_dist(ctx, *input, **kwargs).wait()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/embedding.py", line 325, in input_dist
    tensor_awaitable = tensor_awaitable.wait()  # finish lengths all2all
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 117, in wait
    ret: W = self._wait_impl()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 112, in _wait_impl
    id_list_features_awaitable=self._id_list_features_awaitable.wait()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 117, in wait
    ret: W = self._wait_impl()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 384, in _wait_impl
    ret = KJTAllToAllIndicesAwaitable(
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 168, in __init__
    out_values = torch.empty(
TypeError: empty(): argument 'size' must be tuple of ints, but found element of type int at pos 1
[E ProcessGroupNCCL.cpp:717] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4190, OpType=ALLTOALL_BASE, Timeout(ms)=1800000) ran for 1804588 milliseconds before timing out.
Epoch 9, Rank 6, world_size 8: 17batch [30:06, 106.25s/batch]
Traceback (most recent call last):
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 300, in <module>
    main()
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 253, in main
    train(args, train_pipeline, train_dataloader, rank, world_size)
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 103, in train
    _train(train_pipeline, train_iterator, next_iterator, epoch, rank, world_size)
  File "/GitSource/collaborative_filtering/src/main_torchrec.py", line 86, in _train
    train_pipeline.progress(combined_iterator)
  File "/GitSource/collaborative_filtering/src/torchrec_pipeline.py", line 69, in progress
    (losses, output) = cast(Tuple[torch.Tensor, Out], self._model(batch_i))
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 245, in forward
    return self._dmp_wrapped_module(*args, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/GitSource/collaborative_filtering/src/torchrec_model.py", line 240, in forward
    loss = self.model.contrastive_loss(
  File "/GitSource/collaborative_filtering/src/torchrec_model.py", line 153, in contrastive_loss
    pos_items: Tensor = self.item_embedding(pos_features)["items"].values()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 415, in forward
    dist_input = self.input_dist(ctx, *input, **kwargs).wait()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/embedding.py", line 325, in input_dist
    tensor_awaitable = tensor_awaitable.wait()  # finish lengths all2all
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 117, in wait
    ret: W = self._wait_impl()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 112, in _wait_impl
    id_list_features_awaitable=self._id_list_features_awaitable.wait()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/types.py", line 117, in wait
    ret: W = self._wait_impl()
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 384, in _wait_impl
    ret = KJTAllToAllIndicesAwaitable(
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 175, in __init__
    self._values_awaitable: dist.Work = dist.all_to_all_single(
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2612, in all_to_all_single
    work = group.alltoall_base(
RuntimeError: NCCL communicator was aborted on rank 6.  Original reason for failure was: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4190, OpType=ALLTOALL_BASE, Timeout(ms)=1800000) ran for 1804588 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 2115) of binary: /conda_envs/torchrec_gpu_py39/bin/python
Traceback (most recent call last):
  File "/conda_envs/torchrec_gpu_py39/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0.dev20220307', 'console_scripts', 'torchrun')())
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/conda_envs/torchrec_gpu_py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main_torchrec.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-03-30_06:10:10
  host      : 4fdbdf95bfdd4ade81a50fb8ea6f3c8c-master-0
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 2118)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-03-30_06:10:10
  host      : 4fdbdf95bfdd4ade81a50fb8ea6f3c8c-master-0
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 2120)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-30_06:10:10
  host      : 4fdbdf95bfdd4ade81a50fb8ea6f3c8c-master-0
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2115)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

My code snippet, using ``DistributedModelParallel`` and ``TrainPipelineSparseDist``:

```Python
    # ProcessGroup
    pg = dist.GroupMember.WORLD
    assert pg is not None, "Process group is not initialized"
    # sharders and planner
    sharding_types = [
        # use ROW_WISE for multi-GPUs
        ShardingType.ROW_WISE.value if dist.get_world_size(pg) > 1 else ShardingType.TABLE_WISE.value,
    ]
    compute_kernels = [
        # EmbeddingComputeKernel.SPARSE.value,
        EmbeddingComputeKernel.BATCHED_FUSED.value,
    ]
    constraints = {
            "t_users": ParameterConstraints(sharding_types=sharding_types, compute_kernels=compute_kernels),
            "t_items": ParameterConstraints(sharding_types=sharding_types, compute_kernels=compute_kernels),
        }

    fused_params = {
        "learning_rate": args.learning_rate,
    }
    sharders = [EmbeddingCollectionSharder(fused_params=fused_params)]

    env = ShardingEnv.from_process_group(pg)
    planner = EmbeddingShardingPlanner(
        topology=Topology(
            world_size=env.world_size, compute_device=device.type,
        ),
        constraints=constraints,
    )
    if pg is not None:
        plan = planner.collective_plan(train_model, sharders, pg)
    else:
        plan = planner.plan(train_model, sharders)

    model = DistributedModelParallel(
        module=train_model,
        sharders=cast(List[ModuleSharder[nn.Module]], sharders),
        plan=plan,
        env=env,
        device=device,
    )
    print("model.plan: ", model.plan)
    print("model: ", model)

    # optimizer = KeyedOptimizerWrapper(
    #     dict(model.named_parameters()),
    #     lambda params: torch.optim.SGD(params, lr=args.learning_rate),
    # )

    train_pipeline = TrainPipelineSparseDist(
        model,
        model.fused_optimizer,
        device,
    )

```

**Comment by divchenko** [comment]
How does each rank read data? It's a caller's responsibility to ensure that all ranks have exactly same amount of batches. I guess for convenience-sake we can introduce a helper class - it will ensure that all ranks stop at the same time if at least one rank runs out of data.

**Comment by BackNode** [comment]
Thanks to @divchenko ! 
It works good after I make sure that all ranks have exactly same amount of batches.

**Comment by colin2328** [comment]
@BackNode  closing this issue

**Comment by cwqnewsbreak** [comment]
Do we have this kind of a helper class now

> How does each rank read data? It's a caller's responsibility to ensure that all ranks have exactly same amount of batches. I guess for convenience-sake we can introduce a helper class - it will ensure that all ranks stop at the same time if at least one rank runs out of data.
