### ISSUE TITLE
Import fails (fbgemm_gpu_py.so is required) 

### ISSUE THREAD

**Issue by a-v-ershov** [meta-pytorch/torchrec#210]
## Hardware
* Macbook with M1Max 

## Steps to reproduce
* Install Conda (4.12.0)
* Create and activate conda environment with Python 3.9
* Install CPU version of the library
    * `conda install pytorch cpuonly -c pytorch-nightly`
    * `pip install torchrec-nightly-cpu`
* Run `import torchrec` in a Python console

## Error
```
Python 3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/__init__.py", line 39, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 19, in <module>
    from torchrec.distributed.embeddingbag import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 27, in <module>
    from torchrec.distributed.embedding_sharding import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 14, in <module>
    from torchrec.distributed.dist_data import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 15, in <module>
    from torchrec.distributed.comm_ops import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 27, in <module>
    import fbgemm_gpu  # @manual # noqa
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torch/_ops.py", line 244, in load_library
    ctypes.CDLL(path)
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so, 0x0006): tried: '/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file)
```

**Comment by YLGH** [comment]
hey @ershovio , could you provide the exact commands you used to see this?

I wasn't able to reproduce it with the following:

```
conda create -n debug_import_fails_3.9 --python=3.9
conda activate debug_import_fails_3.9
conda install pytorch cpuonly -c pytorch-nightly
pip install torchrec-nightly-cpu
python -c "import torchrec"
```

**Comment by YLGH** [comment]
I see that you're using miniconda - maybe that's the issue?

**Comment by joshuadeng** [comment]
Might be related to: https://github.com/pytorch/FBGEMM/pull/1039

**Comment by a-v-ershov** [comment]
@YLGH  the full list of commands:

```
conda create -n torchrec_test python=3.9
conda activate torchrec_test
conda install pytorch cpuonly -c pytorch-nightly
pip install torchrec-nightly-cpu
python -c "import torchrec"
```

Error:
```
(torchrec_test) aershov@aleksandrsmbp2 core-hosted-model-project % python -c "import torchrec"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/__init__.py", line 39, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 19, in <module>
    from torchrec.distributed.embeddingbag import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 27, in <module>
    from torchrec.distributed.embedding_sharding import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 14, in <module>
    from torchrec.distributed.dist_data import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 15, in <module>
    from torchrec.distributed.comm_ops import (
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 27, in <module>
    import fbgemm_gpu  # @manual # noqa
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/torch/_ops.py", line 244, in load_library
    ctypes.CDLL(path)
  File "/opt/miniconda3/envs/torchrec_test/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so, 0x0006): tried: '/opt/miniconda3/envs/torchrec_test/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file)
```

**Comment by YLGH** [comment]
@ershovio FBGEMM recently fixed an import error

https://github.com/KanchiShimono/FBGEMM/commit/3a43238fcc44192211eace78fc339d6efb75c5e5

Maybe this could fix your issue?

**Comment by a-v-ershov** [comment]
@YLGH just checked - the same error

**Comment by YLGH** [comment]
@ershovio  

Sorry, I just realized that the issue is likely that torchrce is currently only supported on Linux

See
[](https://github.com/pytorch/torchrec#cuda)Experimental binary on Linux for Python 3.7, 3.8 and 3.9 can be installed via pip wheels

**Comment by colin2328** [comment]
yes, right now we require linux (due to fbgemm dependency). We will further clarify in the README

We will update the repo if that changes in the future
