### ISSUE TITLE
Fail to run under CPU mode with error of 'unexpected keyword argument 'static_graph''

### ISSUE THREAD

**Issue by Guobing-Chen** [meta-pytorch/torchrec#224]
Hi, 

I tried to run TorchRec/DLRM example on my X86 CPU platform (Cooperlake). My Pytorch is 1.11, and I installed latest TorchRec master from source, but it returns with below errors when I tried to run the DLRM example. Could you help me on this?

### Hardware
Cooperlake 8380

### Steps to reproduce
Create and activate conda environment with Python 3.9
Install CPU version of the library from latest master
> python setup.py install --cpu_only 

Run the DLRM example
> torchx run -s local_cwd dist.ddp -j 1x2 --script dlrm_main.py

### Error
dlrm_main/0 [0]:Traceback (most recent call last):
dlrm_main/0 [1]:Traceback (most recent call last):
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/torchrec/examples/dlrm/dlrm_main.py", line 550, in <module>
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/torchrec/examples/dlrm/dlrm_main.py", line 550, in <module>
dlrm_main/0 [0]:    main(sys.argv[1:])
dlrm_main/0 [1]:    main(sys.argv[1:])
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/torchrec/examples/dlrm/dlrm_main.py", line 528, in main
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/torchrec/examples/dlrm/dlrm_main.py", line 528, in main
dlrm_main/0 [0]:    model = DistributedModelParallel(
dlrm_main/0 [1]:    model = DistributedModelParallel(
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 224, in __init__
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 224, in __init__
dlrm_main/0 [0]:    self.init_data_parallel()
dlrm_main/0 [1]:    self.init_data_parallel()
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 259, in init_data_parallel
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 259, in init_data_parallel
dlrm_main/0 [0]:    self._data_parallel_wrapper.wrap(self, self._env, self.device)
dlrm_main/0 [1]:    self._data_parallel_wrapper.wrap(self, self._env, self.device)
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 104, in wrap
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 104, in wrap
dlrm_main/0 [0]:    DistributedDataParallel(
dlrm_main/0 [1]:    DistributedDataParallel(
dlrm_main/0 [0]:TypeError: __init__() got an unexpected keyword argument 'static_graph'
dlrm_main/0 [1]:TypeError: __init__() got an unexpected keyword argument 'static_graph'
dlrm_main/0 ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7786) of binary: /home/neo/anaconda3/bin/python
dlrm_main/0 Traceback (most recent call last):
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
dlrm_main/0     return _run_code(code, main_globals, None,
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
dlrm_main/0     exec(code, run_globals)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 728, in <module>
dlrm_main/0     main()
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
dlrm_main/0     return f(*args, **kwargs)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
dlrm_main/0     run(args)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
dlrm_main/0     elastic_launch(
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
dlrm_main/0     return launch_agent(self._config, self._entrypoint, list(args))
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
dlrm_main/0     raise ChildFailedError(
dlrm_main/0 torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
dlrm_main/0 ============================================================
dlrm_main/0 dlrm_main.py FAILED
dlrm_main/0 ------------------------------------------------------------
dlrm_main/0 Failures:
dlrm_main/0 [1]:
dlrm_main/0   time      : *****
dlrm_main/0   host      : *****
dlrm_main/0   rank      : 1 (local_rank: 1)
dlrm_main/0   exitcode  : 1 (pid: 7787)
dlrm_main/0   error_file: <N/A>
dlrm_main/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
dlrm_main/0 ------------------------------------------------------------
dlrm_main/0 Root Cause (first observed failure):
dlrm_main/0 [0]:
dlrm_main/0   time      : *****
dlrm_main/0   host      : *****
dlrm_main/0   rank      : 0 (local_rank: 0)
dlrm_main/0   exitcode  : 1 (pid: 7786)
dlrm_main/0   error_file: <N/A>
dlrm_main/0   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
dlrm_main/0 ============================================================
torchx 2022-04-14 11:28:54 INFO     Job finished: FAILED
torchx 2022-04-14 11:28:54 ERROR    AppStatus:

**Comment by YLGH** [comment]
Hey @Guobing-Chen 

Could you share the list of commands you used to activate conda + install dependencies?

I tried to reproduce this, but we were able to get past the creation of DistributedModelParallel, which is were your issue is happening.

In addition, could you try running the test_installation script on the github to see if things are working?

**Comment by Guobing-Chen** [comment]
Hi YLGH,

Thanks for quick response. I see there is a big change of this repo and dlrm example is moved to the dedicated dlrm repo. So I updated the repo code and created a fresh env to re-do the setup, however the error turns to be different now. Below is the steps of my setup.

Firstly I use docker env to manage all my work. So I start all the things with a Ubuntu20.04 docker base.
1. Ubuntu20.04 docker base with GCC updated to gcc-10
2. Install anaconda in the docker with its package from its website (Anaconda3-2021.11-Linux-x86_64.sh)
3. With anaconda's base env activated as default, I installed python3.9, numpy, these common python packages.
4. Then install pytorch 1.11 with the cmd from its website: `conda install pytorch torchvision torchaudio cpuonly -c pytorch`
5. Download TorchRec source code from your git repo and keep the master branch
6. Install depencies as following your official installation steps: `pip install -r requirements.txt`
7. Build & Install TorchRec with your suggested cmd for CPU: `python setup.py install --cpu_only`
8. Switch to the DLRM example repo folder (dlrm/torch-dlrm), and install dependencies with: `pip install tqdm torchmetrics`
9. Run with torchx under local mode: `torchx run -s local_cwd dist.ddp -j 1x2 --script dlrm_main.py`

It will then show errors like below:
```
dlrm_main/0 WARNING:__main__:
dlrm_main/0 *****************************************
dlrm_main/0 Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
dlrm_main/0 *****************************************
dlrm_main/0 [0]:
dlrm_main/0 [0]:Epoch 0: 0it [00:00, ?it/s]
dlrm_main/0 [0]:Epoch 0: 0it [00:00, ?it/s]
dlrm_main/0 [0]:Traceback (most recent call last):
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 550, in <module>
dlrm_main/0 [0]:    main(sys.argv[1:])
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 544, in main
dlrm_main/0 [0]:    train_val_test(
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 405, in train_val_test
dlrm_main/0 [0]:    _train(
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 344, in _train
dlrm_main/0 [0]:    train_pipeline.progress(combined_iterator)
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/train_pipeline.py", line 499, in progress
dlrm_main/0 [0]:    self._connect(dataloader_iter)
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/train_pipeline.py", line 475, in _connect
dlrm_main/0 [0]:    model(self._batch_i)
dlrm_main/0 [1]:
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:Epoch 0: 0it [00:00, ?it/s]
dlrm_main/0 [0]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:Epoch 0: 0it [00:00, ?it/s]
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 248, in forward
dlrm_main/0 [1]:Traceback (most recent call last):
dlrm_main/0 [0]:    return self._dmp_wrapped_module(*args, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 550, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:    main(sys.argv[1:])
dlrm_main/0 [0]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 544, in main
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 965, in forward
dlrm_main/0 [1]:    train_val_test(
dlrm_main/0 [0]:    output = self.module(*inputs, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 405, in train_val_test
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:    _train(
dlrm_main/0 [0]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 344, in _train
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/modules/dlrm_train.py", line 79, in forward
dlrm_main/0 [1]:    train_pipeline.progress(combined_iterator)
dlrm_main/0 [0]:    logits = self.model(batch.dense_features, batch.sparse_features)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/train_pipeline.py", line 499, in progress
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:    self._connect(dataloader_iter)
dlrm_main/0 [0]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/train_pipeline.py", line 475, in _connect
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/models/dlrm.py", line 398, in forward
dlrm_main/0 [1]:    model(self._batch_i)
dlrm_main/0 [0]:    embedded_sparse = self.sparse_arch(sparse_features)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:    return forward_call(*input, **kwargs)
dlrm_main/0 [0]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/model_parallel.py", line 248, in forward
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/models/dlrm.py", line 101, in forward
dlrm_main/0 [1]:    return self._dmp_wrapped_module(*args, **kwargs)
dlrm_main/0 [0]:    sparse: Dict[str, torch.Tensor] = sparse_features.to_dict()
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 234, in __getattr__
dlrm_main/0 [1]:    return forward_call(*input, **kwargs)
dlrm_main/0 [0]:    res = LazyAwaitable._wait_async(self)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 965, in forward
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 193, in _wait_async
dlrm_main/0 [1]:    output = self.module(*inputs, **kwargs)
dlrm_main/0 [0]:    obj._result = obj.wait()
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 120, in wait
dlrm_main/0 [1]:    return forward_call(*input, **kwargs)
dlrm_main/0 [0]:    ret: W = self._wait_impl()
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/modules/dlrm_train.py", line 79, in forward
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/embeddingbag.py", line 213, in _wait_impl
dlrm_main/0 [1]:    logits = self.model(batch.dense_features, batch.sparse_features)
dlrm_main/0 [0]:    embeddings = [w.wait() for w in self._awaitables]
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/embeddingbag.py", line 213, in <listcomp>
dlrm_main/0 [1]:    return forward_call(*input, **kwargs)
dlrm_main/0 [0]:    embeddings = [w.wait() for w in self._awaitables]
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/models/dlrm.py", line 398, in forward
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 122, in wait
dlrm_main/0 [1]:    embedded_sparse = self.sparse_arch(sparse_features)
dlrm_main/0 [0]:    ret = callback(ret)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:    return forward_call(*input, **kwargs)
dlrm_main/0 [0]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/models/dlrm.py", line 101, in forward
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/fbgemm_gpu/permute_pooled_embedding_modules.py", line 66, in forward
dlrm_main/0 [1]:    sparse: Dict[str, torch.Tensor] = sparse_features.to_dict()
dlrm_main/0 [0]:    result = torch.ops.fbgemm.permute_pooled_embs_auto_grad(
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 234, in __getattr__
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 167, in __getattr__
dlrm_main/0 [1]:    res = LazyAwaitable._wait_async(self)
dlrm_main/0 [0]:    op = torch._C._jit_get_operation(qualified_op_name)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 193, in _wait_async
dlrm_main/0 [0]:RuntimeError: No such operator fbgemm::permute_pooled_embs_auto_grad
dlrm_main/0 [1]:    obj._result = obj.wait()
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 120, in wait
dlrm_main/0 [1]:    ret: W = self._wait_impl()
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/embeddingbag.py", line 213, in _wait_impl
dlrm_main/0 [1]:    embeddings = [w.wait() for w in self._awaitables]
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/embeddingbag.py", line 213, in <listcomp>
dlrm_main/0 [1]:    embeddings = [w.wait() for w in self._awaitables]
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/torchrec/distributed/types.py", line 122, in wait
dlrm_main/0 [1]:    ret = callback(ret)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
dlrm_main/0 [1]:    return forward_call(*input, **kwargs)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec-0.1.0-py3.9.egg/fbgemm_gpu/permute_pooled_embedding_modules.py", line 66, in forward
dlrm_main/0 [1]:    result = torch.ops.fbgemm.permute_pooled_embs_auto_grad(
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 167, in __getattr__
dlrm_main/0 [1]:    op = torch._C._jit_get_operation(qualified_op_name)
dlrm_main/0 [1]:RuntimeError: No such operator fbgemm::permute_pooled_embs_auto_grad
dlrm_main/0 ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2877) of binary: /home/neo/anaconda3/bin/python
dlrm_main/0 Traceback (most recent call last):
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
dlrm_main/0     return _run_code(code, main_globals, None,
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
dlrm_main/0     exec(code, run_globals)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 728, in <module>
dlrm_main/0     main()
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
dlrm_main/0     return f(*args, **kwargs)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
dlrm_main/0     run(args)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
dlrm_main/0     elastic_launch(
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
dlrm_main/0     return launch_agent(self._config, self._entrypoint, list(args))
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
dlrm_main/0     raise ChildFailedError(
dlrm_main/0 torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

Seems like there is something wrong with fbgemm. I then tried to install torchrec nightly build binary with cmd:
`pip install torchrec-nightly-cpu`
It will also install a fbgemm_gpu package under python3.9/site-package. (A bit wired that I installed the torchrec cpu version but why fbgemm_gpu is installed). And after I run the same torchx cmd for dlrm example, it turns to be another error:
```
dlrm_main/0 *****************************************
dlrm_main/0 [0]:Traceback (most recent call last):
dlrm_main/0 [0]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 20, in <module>
dlrm_main/0 [1]:Traceback (most recent call last):
dlrm_main/0 [0]:    from torchrec import EmbeddingBagCollection
dlrm_main/0 [1]:  File "/home/neo/workspace/projects/torchrec/dlrm/torchrec_dlrm/dlrm_main.py", line 20, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/__init__.py", line 8, in <module>
dlrm_main/0 [1]:    from torchrec import EmbeddingBagCollection
dlrm_main/0 [0]:    import torchrec.distributed  # noqa
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/__init__.py", line 8, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/__init__.py", line 39, in <module>
dlrm_main/0 [1]:    import torchrec.distributed  # noqa
dlrm_main/0 [0]:    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/__init__.py", line 39, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 20, in <module>
dlrm_main/0 [1]:    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
dlrm_main/0 [0]:    from torchrec.distributed.embeddingbag import (
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 20, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 27, in <module>
dlrm_main/0 [1]:    from torchrec.distributed.embeddingbag import (
dlrm_main/0 [0]:    from torchrec.distributed.embedding_sharding import (
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 27, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 14, in <module>
dlrm_main/0 [1]:    from torchrec.distributed.embedding_sharding import (
dlrm_main/0 [0]:    from torchrec.distributed.dist_data import (
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/embedding_sharding.py", line 14, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 15, in <module>
dlrm_main/0 [1]:    from torchrec.distributed.dist_data import (
dlrm_main/0 [0]:    from torchrec.distributed.comm_ops import (
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 15, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 27, in <module>
dlrm_main/0 [1]:    from torchrec.distributed.comm_ops import (
dlrm_main/0 [0]:    import fbgemm_gpu  # @manual # noqa
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 27, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
dlrm_main/0 [1]:    import fbgemm_gpu  # @manual # noqa
dlrm_main/0 [0]:    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
dlrm_main/0 [1]:    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
dlrm_main/0 [0]:    ctypes.CDLL(path)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
dlrm_main/0 [0]:  File "/home/neo/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
dlrm_main/0 [1]:    ctypes.CDLL(path)
dlrm_main/0 [0]:    self._handle = _dlopen(self._name, mode)
dlrm_main/0 [1]:  File "/home/neo/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
dlrm_main/0 [0]:OSError: /home/neo/anaconda3/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK3c1011DynamicType11dynamicKindEv
dlrm_main/0 [1]:    self._handle = _dlopen(self._name, mode)
dlrm_main/0 [1]:OSError: /home/neo/anaconda3/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK3c1011DynamicType11dynamicKindEv
dlrm_main/0 ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2906) of binary: /home/neo/anaconda3/bin/python
dlrm_main/0 Traceback (most recent call last):
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
dlrm_main/0     return _run_code(code, main_globals, None,
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
dlrm_main/0     exec(code, run_globals)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 728, in <module>
dlrm_main/0     main()
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
dlrm_main/0     return f(*args, **kwargs)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
dlrm_main/0     run(args)
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
dlrm_main/0     elastic_launch(
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
dlrm_main/0     return launch_agent(self._config, self._entrypoint, list(args))
dlrm_main/0   File "/home/neo/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
dlrm_main/0     raise ChildFailedError(
dlrm_main/0 torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

This seems that the fbgemm_gpu package is with problem that some related .so is not met.

**Comment by YLGH** [comment]
@Guobing-Chen QQ, what OS are you running with? TorchRec only works on linux currently

**Comment by Guobing-Chen** [comment]
Both my docker env and host env is Ubuntu20.04 LTS.

**Comment by YLGH** [comment]
@Guobing-Chen 
FBGEMM had a regression that led to these ops not being supported on CPU, and they're working on fixing it (changes should be landed relatively soon).

In the meantime, they recommended to try to build FBGEMM off of the commit id
https://github.com/pytorch/FBGEMM/commit/0221cd8813ab8385c32b5ddfa83b0dc4bae73b55 
some instructions here
https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu#build-from-source

(I'll try to get this working as well, but may take a while)

**Comment by Guobing-Chen** [comment]
@YLGH 
Thank much for quickly figuring out this issue. Will TorchRec temporarily changes to this special FBGEMM commit during the fixing phase of FBGEMM community?

**Comment by YLGH** [comment]
hey @Guobing-Chen , FBGEMM has fixed the CPU Op incompatibility. If you pull the latest nightly, this should be resolved. Let us know if you have any other issues!

**Comment by Guobing-Chen** [comment]
Sounds great. Thanks for the information and help.
