### ISSUE TITLE
How to run sharded DLRM inference on multi-process CPU environment?

### ISSUE THREAD

**Issue by JiinKim0102** [meta-pytorch/torchrec#229]
Hi, I appriciate your work on this project.

I want to test simple sharded DLRM inference on CPU environment.
But I'm not sure how to run inference on multi-process.

### Setup commands are
```
conda create -n tochrec python=3.9
conda activate torchrec
conda install pytorch cpuonly -c pytorch-nightly
pip install torchrec-nightly-cpu
```

**First**, I'm wondering how to seperate master and worker processes. 
I want the master to send an inference request to the worker and the worker to wait an request.
Then, the worker and the master lookup allocated shards and the master gathers output.
Could you give me some example code to seperate master and worker processes?

**Second**, errors occurred when inferencing CW and RW shards using multi-process. Is there something wrong with my code or command?

### Error message on CW sharding:

```
============================================================
dlrm_sharding.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-04-17_08:47:12
  host      : node10
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 277843)
  error_file: /tmp/torchelastic__lprh9al/none_qcpp0gvj/attempt_0/1/error.json
  traceback : Traceback (most recent call last):
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
      return func(*args, **kwargs)
    File "/home/jiin/2022/torchrec/dlrm_sharding.py", line 152, in main
      logits = model.forward(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 248, in forward
      return self._dmp_wrapped_module(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 989, in forward
      output = self.module(*inputs, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 398, in forward
      embedded_sparse = self.sparse_arch(sparse_features)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 101, in forward
      sparse: Dict[str, torch.Tensor] = sparse_features.to_dict()
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 234, in __getattr__
      res = LazyAwaitable._wait_async(self)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 193, in _wait_async
      obj._result = obj.wait()
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 120, in wait
      ret: W = self._wait_impl()
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 213, in _wait_impl
      embeddings = [w.wait() for w in self._awaitables]
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 213, in <listcomp>
      embeddings = [w.wait() for w in self._awaitables]
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 122, in wait
      ret = callback(ret)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/fbgemm_gpu/permute_pooled_embedding_modules.py", line 66, in forward
      result = torch.ops.fbgemm.permute_pooled_embs_auto_grad(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/_ops.py", line 191, in __getattr__
      op = torch._C._jit_get_operation(qualified_op_name)
  RuntimeError: No such operator fbgemm::permute_pooled_embs_auto_grad
  
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-17_08:47:12
  host      : node10
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 277842)
  error_file: /tmp/torchelastic__lprh9al/none_qcpp0gvj/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
      return func(*args, **kwargs)
    File "/home/jiin/2022/torchrec/dlrm_sharding.py", line 152, in main
      logits = model.forward(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 248, in forward
      return self._dmp_wrapped_module(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 989, in forward
      output = self.module(*inputs, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 398, in forward
      embedded_sparse = self.sparse_arch(sparse_features)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 101, in forward
      sparse: Dict[str, torch.Tensor] = sparse_features.to_dict()
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 234, in __getattr__
      res = LazyAwaitable._wait_async(self)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 193, in _wait_async
      obj._result = obj.wait()
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 120, in wait
      ret: W = self._wait_impl()
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 213, in _wait_impl
      embeddings = [w.wait() for w in self._awaitables]
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 213, in <listcomp>
      embeddings = [w.wait() for w in self._awaitables]
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 122, in wait
      ret = callback(ret)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/fbgemm_gpu/permute_pooled_embedding_modules.py", line 66, in forward
      result = torch.ops.fbgemm.permute_pooled_embs_auto_grad(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/_ops.py", line 191, in __getattr__
      op = torch._C._jit_get_operation(qualified_op_name)
  RuntimeError: No such operator fbgemm::permute_pooled_embs_auto_grad
  
============================================================
```

### Error message on RW sharding:
```
============================================================
dlrm_sharding.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-04-17_08:48:09
  host      : node10
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 277932)
  error_file: /tmp/torchelastic_jckpsnqi/none_y6iove8k/attempt_0/1/error.json
  traceback : Traceback (most recent call last):
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
      return func(*args, **kwargs)
    File "/home/jiin/2022/torchrec/dlrm_sharding.py", line 152, in main
      logits = model.forward(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 248, in forward
      return self._dmp_wrapped_module(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 989, in forward
      output = self.module(*inputs, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 398, in forward
      embedded_sparse = self.sparse_arch(sparse_features)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 97, in forward
      sparse_features: KeyedTensor = self.embedding_bag_collection(features)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 422, in forward
      return self.compute_and_output_dist(ctx, dist_input)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 392, in compute_and_output_dist
      awaitables=[
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 393, in <listcomp>
      dist(lookup(features))
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/sharding/rw_sharding.py", line 341, in forward
      return self._dist(local_embs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 792, in forward
      tensor_awaitable = reduce_scatter_pooled(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 413, in reduce_scatter_pooled
      ReduceScatter_Req.apply(group, myreq, rsi, *inputs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 866, in forward
      req = dist.reduce_scatter(output, list(inputs), group=pg, async_op=True)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2454, in reduce_scatter
      work = group.reduce_scatter([output], [input_list], opts)
  RuntimeError: ProcessGroupGloo does not support reduce_scatter
  
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-17_08:48:09
  host      : node10
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 277931)
  error_file: /tmp/torchelastic_jckpsnqi/none_y6iove8k/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
      return func(*args, **kwargs)
    File "/home/jiin/2022/torchrec/dlrm_sharding.py", line 152, in main
      logits = model.forward(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 248, in forward
      return self._dmp_wrapped_module(*args, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 989, in forward
      output = self.module(*inputs, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 398, in forward
      embedded_sparse = self.sparse_arch(sparse_features)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/models/dlrm.py", line 97, in forward
      sparse_features: KeyedTensor = self.embedding_bag_collection(features)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/types.py", line 422, in forward
      return self.compute_and_output_dist(ctx, dist_input)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 392, in compute_and_output_dist
      awaitables=[
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 393, in <listcomp>
      dist(lookup(features))
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/sharding/rw_sharding.py", line 341, in forward
      return self._dist(local_embs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/dist_data.py", line 792, in forward
      tensor_awaitable = reduce_scatter_pooled(
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 413, in reduce_scatter_pooled
      ReduceScatter_Req.apply(group, myreq, rsi, *inputs)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/comm_ops.py", line 866, in forward
      req = dist.reduce_scatter(output, list(inputs), group=pg, async_op=True)
    File "/home/jiin/anaconda3/envs/torchrec/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2454, in reduce_scatter
      work = group.reduce_scatter([output], [input_list], opts)
  RuntimeError: ProcessGroupGloo does not support reduce_scatter
  
============================================================
```

Here are my code and command.

### Code:

```
class RWSharder(EmbeddingBagCollectionSharder):
    def sharding_types(self, compute_device_type: str) -> List[str]:
        return [ShardingType.ROW_WISE.value]

    def compute_kernels(
        self, sharding_type: str, compute_device_type: str
    ) -> List[str]:
        return [EmbeddingComputeKernel.DENSE.value]

class CWSharder(EmbeddingBagCollectionSharder):
    def sharding_types(self, compute_device_type: str) -> List[str]:
        return [ShardingType.COLUMN_WISE.value]

    def compute_kernels(
        self, sharding_type: str, compute_device_type: str
    ) -> List[str]:
        return [EmbeddingComputeKernel.DENSE.value]

@torch.no_grad()
def main():

    dist.init_process_group(
        backend="gloo"
    )

    ebc = torchrec.EmbeddingBagCollection(
        device="cpu",
        tables=[
            torchrec.EmbeddingBagConfig(
                name="product_table",
                embedding_dim=D,
                num_embeddings=E,
                feature_names=["product"],
                pooling=torchrec.PoolingType.SUM,
            ),
            torchrec.EmbeddingBagConfig(
                name="user_table",
                embedding_dim=D,
                num_embeddings=E,
                feature_names=["user"],
                pooling=torchrec.PoolingType.SUM,
            )
        ]
    )

    dlrm = torchrec.models.dlrm.DLRM(
        embedding_bag_collection=ebc,
        dense_in_features=100,
        dense_arch_layer_sizes=[128, D],
        over_arch_layer_sizes=[D, 32, 1],
    )

    sharders = [cast(ModuleSharder[torch.nn.Module], RWSharder())]

    model = torchrec.distributed.DistributedModelParallel(
                dlrm, 
                device=torch.device("cpu"), 
                sharders=sharders,
            )

    # features
    dense_features = torch.ones((B, 100))
    sparse_features = torchrec.KeyedJaggedTensor(
        keys = ["product", "user"],
        values = torch.tensor([101, 202, 303, 404, 505, 606, 707]),
        lengths = torch.tensor([2, 1, 1, 1, 1, 1]),
    )

    logits = model.forward(
        dense_features=dense_features,
        sparse_features=sparse_features,
    )
    print(logits)

if __name__ == "__main__":
    main()
```
### Command:
```
torchrun --nproc_per_node 2 dlrm_sharding.py
```

**Comment by YLGH** [comment]
Hey @JiinKim0102, for the issues you're seeing:

1. RW Sharding,

This is actually not compatible with Gloo backend. We've recently made some changes on our side to remove this as a sharding option for non NCCL backends.

2. CW Sharding

FBGEMM recently had a regression that led to these ops not being supported on CPU, and they're working on fixing it (changes should be landed relatively soon).

In the meantime, they recommended to try to build FBGEMM off of the commit id
https://github.com/pytorch/FBGEMM/commit/0221cd8813ab8385c32b5ddfa83b0dc4bae73b55 
some instructions here
https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu#build-from-source

(I'll try to get this working as well, but may take a while)

**Comment by YLGH** [comment]
@JiinKim0102 the fbgemm issue should be resolved by now. Let us know if you have any further issues getting the cpu version w/ CW sharding to work.
