### ISSUE TITLE
[M3 Mac] Fresh install error. Running into - fbgemm_gpu_py.so' (no such file)

### ISSUE THREAD

**Issue by wlrd** [meta-pytorch/torchrec#2338]
I created a fresh conda environment with the following steps.
1. conda create -n "test_ml" python=3.10
2. conda install pytorch::pytorch torchvision torchaudio -c pytorch
3. pip install torchrec

This all runs fine and seems to install properly. I run into the following when trying to import torchrec on a M3 Mac. 
```
>>> import torchrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/torchrec/distributed/__init__.py", line 8, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/torchrec/distributed/model_parallel.py", line 17, in <module>
    from torchrec.distributed.embeddingbag import (
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/torchrec/distributed/embeddingbag.py", line 28, in <module>
    from torchrec.distributed.cw_sharding import CwEmbeddingSharding
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/torchrec/distributed/cw_sharding.py", line 12, in <module>
    from fbgemm_gpu.permute_pooled_embedding_modules import PermutePooledEmbeddings
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so, 0x0006): tried: '/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (no such file), '/opt/homebrew/Caskroom/miniconda/base/envs/test_ml/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file)
```

Is there support for torchrec on Apple silicon? I am using a M3 Mac right now.

**Comment by PaulZhang12** [comment]
There is no official support for torchrec on Apple silicon no

**Comment by wlrd** [comment]
Sounds good, thank you.
