### ISSUE TITLE
ImportError: cannot import name 'GetAttrKey' from 'torch.utils._pytree'

### ISSUE THREAD

**Issue by gouchangjiang** [meta-pytorch/torchrec#2371]
Hi, there.  Torchrec v0.8.0 requests a high version of PyTorch. I am using torch 2.2.1+cu118. But it complains that 

> ImportError: cannot import name 'GetAttrKey' from 'torch.utils._pytree'

To reproduce the problem, just run `python -c "from torchrec.sparse.jagged_tensor import JaggedTensor"`. I checked the[ _pytree.py](https://github.com/pytorch/pytorch/blob/v2.2.1/torch/utils/_pytree.py) file of v2.2.1, GetAttrKey is not defined.  I think we should list the minimum version requirement of the torch in the installation section of torchrec.  The full stacktrace is attached below. 

> /opt/conda/envs/python3.8.13/lib/python3.8/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK3c105Error4whatEv
/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/fbgemm_gpu/experimental/gen_ai/fbgemm_gpu_experimental_gen_ai_py.so: undefined symbol: _ZNK3c105Error4whatEv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/__init__.py", line 10, in <module>
    import torchrec.distributed  # noqa
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/distributed/__init__.py", line 38, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 26, in <module>
    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/distributed/planner/__init__.py", line 24, in <module>
    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/distributed/planner/planners.py", line 21, in <module>
    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/distributed/planner/constants.py", line 12, in <module>
    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/distributed/embedding_types.py", line 30, in <module>
    from torchrec.modules.embedding_configs import (
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/modules/__init__.py", line 26, in <module>
    from . import (  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa  # noqa
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/modules/embedding_modules.py", line 21, in <module>
    from torchrec.modules.utils import is_non_strict_exporting, register_custom_op
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/modules/utils.py", line 18, in <module>
    from torchrec.sparse.jagged_tensor import (
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/sparse/__init__.py", line 35, in <module>
    from . import jagged_tensor  # noqa
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torchrec/sparse/jagged_tensor.py", line 19, in <module>
    from torch.utils._pytree import GetAttrKey, KeyEntry, register_pytree_node
ImportError: cannot import name 'GetAttrKey' from 'torch.utils._pytree' (/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/utils/_pytree.py)

**Comment by gouchangjiang** [comment]
BTW, the minimum version of torch that has `GetAttrKey` defind in `torch.utils._pytree` is 2.3.0

**Comment by PaulZhang12** [comment]
Hi @gouchangjiang, torchrec version v0.8.0 corresponds with pytorch 2.4.0. TorchRec releases everytime that PyTorch does, so for example, v0.7.0 corresponds with PyTorch 2.3.0. If you need to use an earlier version of pytorch, you need to use an earlier version of Torchrec

**Comment by gouchangjiang** [comment]
thanks @PaulZhang12
