### ISSUE TITLE
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pxwang3** [meta-pytorch/torchrec#249]
----------- solved ---------

Getting pytorch-1.12.0.dev20220420 as of today. This version works.

----------------------------

Original issue:

`import torch; print(torch.__version__)` gives `1.11.0+cu102`

I wonder if the cuda version is incorrect. However 
`conda install pytorch cudatoolkit=11.3 -c pytorch-nightly`
either gives me pytorch version 1.10.0 (with CUDA 11.3), or pytorch version 1.11.0 (with CUDA 10.2 I suppose?). For pytorch==1.10.0 there's another error complaining `ModuleNotFoundError: No module named 'torch.distributed.fsdp'`. So I guess we have to use pytorch 1.11.0.

Detailed error messages:
```
>>> import torchrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/distributed/__init__.py", line 39, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 20, in <module>
    from torchrec.distributed.embeddingbag import (
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 27, in <module>
    from torchrec.distributed.embedding_sharding import (
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/distributed/embedding_sharding.py", line 14, in <module>
    from torchrec.distributed.dist_data import (
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/distributed/dist_data.py", line 15, in <module>
    from torchrec.distributed.comm_ops import (
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torchrec/distributed/comm_ops.py", line 27, in <module>
    import fbgemm_gpu  # @manual # noqa
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```

**Comment by BitcoinNLPer** [comment]
Same issue

**Comment by feifeifei12** [comment]
I have the same problem. Could you tell how to deal with it ?
