### ISSUE TITLE
Can't install torchrec-nightly on fresh conda environment

### ISSUE THREAD

**Issue by getchebarne** [meta-pytorch/torchrec#319]
Hello,

I'm unable to install torchrec-nightly on conda on a brand new environment. I reproduced the installation guide on the documentation, i.e., ran the following commands: 

```
conda install pytorch cudatoolkit=11.3 -c pytorch-nightly
pip install torchrec-nightly
```

However, when I import torchrec, I get the following error:

```
(torchrec) jupyter@ctr-model-gpu:~$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/distributed/__init__.py", line 39, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/distributed/model_parallel.py", line 20, in <module>
    from torchrec.distributed.embeddingbag import (
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/distributed/embeddingbag.py", line 27, in <module>
    from torchrec.distributed.embedding_sharding import (
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/distributed/embedding_sharding.py", line 14, in <module>
    from torchrec.distributed.dist_data import (
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/distributed/dist_data.py", line 15, in <module>
    from torchrec.distributed.comm_ops import (
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torchrec/distributed/comm_ops.py", line 27, in <module>
    import fbgemm_gpu  # @manual # noqa
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/opt/conda/envs/torchrec/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/opt/conda/envs/torchrec/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/envs/torchrec/lib/python3.8/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN3c1021getCustomClassTypeMapEv
```

Any idea on what might be happening?

**Comment by getchebarne** [comment]
I'm also getting an error trying to install torchrec from source. I followed the steps in the documentation (also installed FBGEMM from source) and ran `python setup.py install develop --skip_fbgemm`, but now I'm getting this error:

```
(torchrec) jupyter@ctr-model-gpu-a100:~/torchrec$ python setup.py install develop --skip_fbgemm
['setup.py', 'install', 'develop', '--skip_fbgemm']
args:  Namespace(TORCH_CUDA_ARCH_LIST='7.0;8.0', cpu_only=False, package_name='torchrec', skip_fbgemm=True)
unknown:  ['install', 'develop']
name:  torchrec
-- torchrec building version: 0.1.0
Skipping fbgemm_gpu installation
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    main(sys.argv[1:])
  File "setup.py", line 118, in main
    fbgemm_install_base = glob.glob(
IndexError: list index out of range
```

**Comment by getchebarne** [comment]
I'm also unable to install torchrec from source. I followed the steps on the installation guide (installed FBGEMM separately), but now I'm getting this error:

```
(torchrec) jupyter@ctr-model-gpu-a100:~/torchrec$ python setup.py install develop --skip_fbgemm
['setup.py', 'install', 'develop', '--skip_fbgemm']
args:  Namespace(skip_fbgemm=True, package_name='torchrec', TORCH_CUDA_ARCH_LIST='7.0;8.0', cpu_only=False)
unknown:  ['install', 'develop']
name:  torchrec
-- torchrec building version: 0.1.0
Skipping fbgemm_gpu installation
Traceback (most recent call last):
  File "/home/jupyter/torchrec/setup.py", line 166, in <module>
    main(sys.argv[1:])
  File "/home/jupyter/torchrec/setup.py", line 118, in main
    fbgemm_install_base = glob.glob(
IndexError: list index out of range
```

**Comment by zxgx** [comment]
Hi, I've just met the same error. Have you resolved this problem?

**Comment by getchebarne** [comment]
hey! I've just followed the instructions to install it from source and it seems to be working now.

**Comment by colin2328** [comment]
@getchebarne , @zxgx
great, glad you had success installing from source.

Right now our nightly build is broken (due to pypi sizing limits, which we're trying to resolve). Please build from source, or try using stable version in the meantime.

**Comment by colin2328** [comment]
@getchebarne @zxgx 

Please use 	
pip install --pre torchrec_nightly -f https://download.pytorch.org/whl/nightly/torchrec_nightly/index.html for the nightly now, we will update the README shortly
