### ISSUE TITLE
Gather Sharded Embedding on multi-GPUs to CPU Memory

### ISSUE THREAD

**Issue by BackNode** [meta-pytorch/torchrec#384]
I am trying to gather Sharded embeddings to rank 0, while met CUDA OOM. Not sure if I am using the correct method, any suggestion?

```Python
def get_user_embeddings(self):
    sd = self.model.state_dict()
    # support multi-GPUs
    user_emb = _collate_sharded_tensor(sd['model.user_embedding.embeddings.t_users.weight'], (self.num_users, self.factors))

def _collate_sharded_tensor(sharded_tensor, size):
    rank = int(os.environ["LOCAL_RANK"])
    out_tensor = torch.empty(size, device=torch.device("cpu")) if rank == 0 else None
    sharded_tensor.gather(0, out_tensor)
    return out_tensor
```

```
2022-05-26 14:54:30 Traceback (most recent call last):
2022-05-26 14:54:30   File "main_torchrec.py", line 431, in <module>
2022-05-26 14:54:30     main()
2022-05-26 14:54:30   File "main_torchrec.py", line 329, in main
2022-05-26 14:54:30     train(args, train_pipeline, train_dataloader, rank, world_size, evaluator)
2022-05-26 14:54:30   File "main_torchrec.py", line 138, in train
2022-05-26 14:54:30     item_emb = evaluator.model.get_item_embeddings()
2022-05-26 14:54:30   File "/tmp/src/torchrec_cf/utils.py", line 54, in get_item_embeddings
2022-05-26 14:54:30     item_emb = _collate_sharded_tensor(sd['model.item_embedding.embeddings.t_items.weight'], (self.num_items, self.factors))
2022-05-26 14:54:30   File "/tmp/src/torchrec_cf/utils.py", line 64, in _collate_sharded_tensor
2022-05-26 14:54:30     sharded_tensor.gather(0, out_tensor)
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/_shard/sharded_tensor/api.py", line 285, in gather
2022-05-26 14:54:30     dist.all_gather_object(
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1668, in all_gather_object
2022-05-26 14:54:30     object_list[i] = _tensor_to_object(tensor, tensor_size)
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1565, in _tensor_to_object
2022-05-26 14:54:30     return _unpickler(io.BytesIO(buf)).load()
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/storage.py", line 181, in _load_from_bytes
2022-05-26 14:54:30     return torch.load(io.BytesIO(b))
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 713, in load
2022-05-26 14:54:30     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 930, in _legacy_load
2022-05-26 14:54:30     result = unpickler.load()
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 876, in persistent_load
2022-05-26 14:54:30     wrap_storage=restore_location(obj, location),
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 176, in default_restore_location
2022-05-26 14:54:30     result = fn(storage, location)
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 156, in _cuda_deserialize
2022-05-26 14:54:30     return storage_type(obj.nbytes())
2022-05-26 14:54:30   File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 661, in _lazy_new
2022-05-26 14:54:30     return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
2022-05-26 14:54:30 RuntimeError: CUDA out of memory. Tried to allocate 1.96 GiB (GPU 0; 79.35 GiB total capacity; 0 bytes already allocated; 718.19 MiB free; 0 bytes reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2022-05-26 14:54:30 
```

**Comment by joshuadeng** [comment]
Hi @BackNode,

One thing, gpu -> cpu transfer is not supported during the gather, so you need to call `sharded_tensor.cpu()` before calling `sharded_tensor.gather()`.

I will follow up more with some folks on PyTorch distributed side.

**Comment by joshuadeng** [comment]
@BackNode which PyTorch version are you using? In the most recent version,`all_gather_object` in the `gather()` call is not being used anymore

**Comment by BackNode** [comment]
Thanks @joshuadeng ! 
Works good after updating pytorch to 1.12-rc3.
```Python
def _collate_sharded_tensor(sharded_tensor, size):
    gloo_pg = dist.new_group(backend="gloo")
    rank = int(os.environ["LOCAL_RANK"])
    out_tensor = torch.empty(size, device=torch.device("cpu")) if rank == 0 else None
    sharded_tensor.cpu(process_group=gloo_pg).gather(0, out_tensor)
    return out_tensor
```
