### ISSUE TITLE
OSError: undefined symbol: _ZN2at6detail20computeStorageNbytesEN3c108ArrayRefIlEES3_mm

### ISSUE THREAD

**Issue by JoshuaQSH** [meta-pytorch/torchrec#392]
Hi,

I followed all the way down to set up torchrec environment but came across an OSError related to fbgemm:
```shell
Traceback (most recent call last):
  File "test_installation.py", line 16, in <module>
    from torchrec import EmbeddingBagCollection, KeyedJaggedTensor
  File "/home/shenghao/torchrec/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/home/shenghao/torchrec/torchrec/distributed/__init__.py", line 36, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/home/shenghao/torchrec/torchrec/distributed/model_parallel.py", line 20, in <module>
    from torchrec.distributed.embedding import EmbeddingCollectionSharder
  File "/home/shenghao/torchrec/torchrec/distributed/embedding.py", line 17, in <module>
    from torchrec.distributed.embedding_sharding import (
  File "/home/shenghao/torchrec/torchrec/distributed/embedding_sharding.py", line 15, in <module>
    from torchrec.distributed.dist_data import (
  File "/home/shenghao/torchrec/torchrec/distributed/dist_data.py", line 15, in <module>
    from torchrec.distributed.comm_ops import (
  File "/home/shenghao/torchrec/torchrec/distributed/comm_ops.py", line 27, in <module>
    import fbgemm_gpu  # @manual  # noqa
  File "/home/shenghao/anaconda3/envs/torchrec/lib/python3.8/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/home/shenghao/anaconda3/envs/torchrec/lib/python3.8/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/home/shenghao/anaconda3/envs/torchrec/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/shenghao/anaconda3/envs/torchrec/lib/python3.8/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN2at6detail20computeStorageNbytesEN3c108ArrayRefIlEES3_mm
```
That happened when I tried to run test_installation.py.
In addition, my CUDA version is 11.6, so I changed all CUDA path-related settings from 11.3 to 11.6.

**Comment by joshuadeng** [comment]
Hi @JoshuaQSH, if you have compiled with 11.x, it should work on the runtime of 11.x (even if x don't match). I'd suggest trying to debug fbgemm_gpu first (i.e, use their nightly and see if it works).

**Comment by JoshuaQSH** [comment]
> Hi @JoshuaQSH, if you have compiled with 11.x, it should work on the runtime of 11.x (even if x don't match). I'd suggest trying to debug fbgemm_gpu first (i.e, use their nightly and see if it works).

Thank you. During debugging fbgemm_gpu, I found out it was the torch version problem and reinstalled the torch 1.13.0.dev. And everything seems all good right now.
