### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by rllin** [meta-pytorch/torchrec#518]
I was trying to update torchrec to `0.2.0` so that I can separate `fbgemm` gpu and cpu (for testing)

I tried with `torch==1.12.0` (released on June 28th?) and `1.13.0.dev20220628`

and both give me this pretty opaque error, any advice?

```
libgcc_s.so.1 must be installed for pthread_cancel to work
[_base._invoke_callbacks:330 - ERROR] exception calling callback for <Future at 0x7f6aeea47460 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/opt/ee/python/3.8/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/common/config_utils.py", line 36, in _done_callback
    future.result()
  File "/opt/ee/python/3.8/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/ee/python/3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
libgcc_s.so.1 must be installed for pthread_cancel to work
Fatal Python error: Aborted

Thread 0x00007f6209ff9700 (most recent call first):
  File "/opt/ee/python/3.8/lib/python3.8/socket.py", line 292 in accept
  File "/opt/ee/python/3.8/lib/python3.8/multiprocessing/connection.py", line 609 in accept
  File "/opt/ee/python/3.8/lib/python3.8/multiprocessing/connection.py", line 463 in accept
  File "/opt/ee/python/3.8/lib/python3.8/multiprocessing/resource_sharer.py", line 142 in _serve
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 870 in run
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f620b7fc700 (most recent call first):
<no Python frame>

Thread 0x00007f620bffd700 (most recent call first):
<no Python frame>

Thread 0x00007f6220ff8700 (most recent call first):
<no Python frame>

Thread 0x00007f62217f9700 (most recent call first):
<no Python frame>

Thread 0x00007f6777fff700 (most recent call first):
  File "/opt/ee/python/3.8/lib/python3.8/concurrent/futures/thread.py", line 78 in _worker
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 870 in run
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f677493f700 (most recent call first):
  File "/opt/ee/python/3.8/lib/python3.8/selectors.py", line 468 in select
  File "/opt/ee/python/3.8/lib/python3.8/asyncio/base_events.py", line 1823 in _run_once
  File "/opt/ee/python/3.8/lib/python3.8/asyncio/base_events.py", line 570 in run_forever
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 870 in run
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/ee/python/3.8/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f6c29c13740 (most recent call first):
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2840 in iterator_get_next
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 783 in _next_internal
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 800 in __next__
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/twitter/ml/torch/experimental/datasets/dataset_lib.py", line 105 in _inner
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 39 in fetch
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 701 in _next_data
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 663 in __next__
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torchrec/distributed/train_pipeline.py", line 490 in progress
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/custom_training_loop.py", line 24 in step_fn
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/custom_training_loop.py", line 123 in train_and_evaluate
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 115 in train
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/twitter/ml/torch/experimental/distributed/training.py", line 39 in maybe_run_training
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 140 in main
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/absl/app.py", line 251 in _run_main
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/absl/app.py", line 300 in run
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 148 in <module>
/opt/ee/python/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 15 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[api._close:697 - WARNING] Sending process 79 closing signal SIGTERM
[api._close:697 - WARNING] Sending process 80 closing signal SIGTERM
[api._close:697 - WARNING] Sending process 81 closing signal SIGTERM
[api._poll:671 - ERROR] failed (exitcode: -6) local_rank: 0 (pid: 78) of binary: /opt/ee/python/3.8/bin/python
[dynamic_rendezvous._close:1128 - INFO] The node 'pytorch-fav-baseline-chief-0_1_0' has closed the rendezvous '79ab6ac2-e83e-4955-87ec-916c3085b103'.
Traceback (most recent call last):
  File "/opt/ee/python/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/ee/python/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 148, in <module>
    app.run(main)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py", line 140, in main
    maybe_run_training(
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/twitter/ml/torch/experimental/distributed/training.py", line 66, in maybe_run_training
    torch.distributed.run.main(cmd)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/ee/python/3.8/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/opt/ee/python/3.8/lib/python3.8/site-packages/large_embeddings/projects/recap/run_native.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-07-11_08:55:06
  host      : pytorch-fav-baseline-chief-0
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 78)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 78
============================================================
libgcc_s.so.1 must be installed for pthread_cancel to work
Fatal Python error: Aborted

Thread 0x00007f3f96992740 (most recent call first):
<no Python frame>
Fatal Python error: Segmentation fault

Thread 0x00007f3f96992740 (most recent call first):
<no Python frame>
```

**Comment by colin2328** [comment]
@rllin  ack will try to repro

**Comment by colin2328** [comment]
@rllin I have tried reproing on fresh conda env (python 3.9.12):
(pip) [colin2328@ip-172-31-16-248 torchrec]$ conda install pytorch  cudatoolkit=11.3 -c pytorch
(pip) [colin2328@ip-172-31-16-248 torchrec]$ pip install torchrec
(pip) [colin2328@ip-172-31-16-248 torchrec]$ torchx run -s local_cwd dist.ddp -j 1x2 --script test_installation.py

which worked fine for me.

this uses:
fbgemm-gpu         0.2.0
torchrec           0.2.0
torchx-nightly     2022.7.11
pytorch                   1.12.0          py3.9_cuda11.3_cudnn8.3.2_0    pytorch

Can you give some more info on your environment? 
At what stage did you get this error? 
Do you have cudatoolkit installed? 
what does (pip) [colin2328@ip-172-31-16-248 torchrec]$ nvcc --version give you?

**Comment by YLGH** [comment]
Is it possible it's an issue/incompatibility with pytorch rather than torchrec - The error stack seems to be coming from torch/utils/data/dataloader

**Comment by colin2328** [comment]
If you can share some code (e.g the important parts from large_embeddings/custom_training_loop.py)
I can take a look

**Comment by rllin** [comment]
i reran a bunch of package installs and this seems fine now.  sorry for the false alarm
