### ISSUE TITLE
state_dict loop test fails on single gpu DLRM model

### ISSUE THREAD

**Issue by mreso** [meta-pytorch/torchrec#546]
Hi,

I am trying to create a single gpu version of the DLRM model like in this example: https://github.com/pytorch/torchrec/blob/main/examples/inference/dlrm_predict_single_gpu.py

When I extract the state_dict from the model and try to load it back into the model I get a key mismatch.
This simple example reproduces the problem:

```python
from dataclasses import dataclass
from typing import List

import fbgemm_gpu  # nopycln: import
import torch
from torchrec.datasets.criteo import DEFAULT_CAT_NAMES, DEFAULT_INT_NAMES
from torchrec.inference.modules import quantize_embeddings
from torchrec.models.dlrm import DLRM
from torchrec.modules.embedding_configs import EmbeddingBagConfig
from torchrec.modules.embedding_modules import EmbeddingBagCollection


def create_default_model_config():
    @dataclass
    class DLRMModelConfig:
        dense_arch_layer_sizes: List[int]
        dense_in_features: int
        embedding_dim: int
        id_list_features_keys: List[str]
        num_embeddings_per_feature: List[int]
        over_arch_layer_sizes: List[int]
    return DLRMModelConfig(
        dense_arch_layer_sizes=[32, 16, 8],
        dense_in_features=len(DEFAULT_INT_NAMES),
        embedding_dim=8,
        id_list_features_keys=DEFAULT_CAT_NAMES,
        num_embeddings_per_feature=len(DEFAULT_CAT_NAMES)
        * [
            3,
        ],
        over_arch_layer_sizes=[32, 32, 16, 1],
    )


class DLRMFactory(type):
    def __new__(cls, model_config=None):

        # If we do not provide a model config we use the default one compatible with the Criteo dataset
        if not model_config:
            model_config = create_default_model_config()

        default_cuda_rank = 0
        device = torch.device("cuda", default_cuda_rank)
        torch.cuda.set_device(device)

        eb_configs = [
            EmbeddingBagConfig(
                name=f"t_{feature_name}",
                embedding_dim=model_config.embedding_dim,
                num_embeddings=model_config.num_embeddings_per_feature[feature_idx],
                feature_names=[feature_name],
            )
            for feature_idx, feature_name in enumerate(
                model_config.id_list_features_keys
            )
        ]
        # Creates an EmbeddingBagCollection without allocating any memory
        ebc = EmbeddingBagCollection(tables=eb_configs, device=device)

        module = DLRM(
            embedding_bag_collection=ebc,
            dense_in_features=model_config.dense_in_features,
            dense_arch_layer_sizes=model_config.dense_arch_layer_sizes,
            over_arch_layer_sizes=model_config.over_arch_layer_sizes,
            dense_device=device,
        )

        module = quantize_embeddings(module, dtype=torch.qint8, inplace=True)

        return module


if __name__ == "__main__":

    model = DLRMFactory()

    state_dict = model.state_dict()

    model.load_state_dict(state_dict)
```

Expected result: That the state_dict get loaded.
Encountered error:
```
Traceback (most recent call last):
  File "/home/ubuntu/serve/examples/torchrec_dlrm/dlrm_factory_repro.py", line 84, in <module>
    model.load_state_dict(state_dict)
  File "/home/ubuntu/miniconda3/envs/dlrm_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DLRM:
        Missing key(s) in state_dict: "sparse_arch.embedding_bag_collection.embedding_bags.0.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.0.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.0.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.0.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.0.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.0.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.0.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.0.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.0.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.0.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.1.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.1.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.1.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.1.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.1.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.1.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.1.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.1.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.1.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.1.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.2.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.2.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.2.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.2.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.2.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.2.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.2.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.2.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.2.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.2.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.3.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.3.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.3.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.3.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.3.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.3.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.3.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.3.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.3.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.3.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.4.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.4.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.4.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.4.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.4.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.4.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.4.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.4.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.4.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.4.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.5.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.5.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.5.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.5.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.5.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.5.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.5.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.5.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.5.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.5.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.6.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.6.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.6.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.6.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.6.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.6.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.6.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.6.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.6.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.6.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.7.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.7.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.7.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.7.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.7.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.7.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.7.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.7.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.7.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.7.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.8.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.8.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.8.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.8.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.8.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.8.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.8.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.8.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.8.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.8.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.9.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.9.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.9.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.9.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.9.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.9.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.9.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.9.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.9.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.9.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.10.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.10.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.10.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.10.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.10.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.10.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.10.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.10.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.10.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.10.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.11.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.11.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.11.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.11.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.11.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.11.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.11.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.11.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.11.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.11.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.12.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.12.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.12.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.12.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.12.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.12.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.12.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.12.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.12.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.12.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.13.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.13.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.13.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.13.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.13.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.13.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.13.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.13.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.13.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.13.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.14.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.14.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.14.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.14.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.14.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.14.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.14.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.14.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.14.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.14.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.15.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.15.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.15.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.15.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.15.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.15.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.15.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.15.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.15.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.15.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.16.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.16.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.16.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.16.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.16.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.16.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.16.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.16.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.16.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.16.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.17.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.17.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.17.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.17.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.17.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.17.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.17.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.17.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.17.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.17.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.18.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.18.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.18.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.18.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.18.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.18.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.18.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.18.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.18.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.18.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.19.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.19.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.19.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.19.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.19.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.19.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.19.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.19.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.19.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.19.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.20.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.20.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.20.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.20.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.20.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.20.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.20.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.20.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.20.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.20.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.21.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.21.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.21.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.21.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.21.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.21.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.21.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.21.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.21.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.21.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.22.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.22.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.22.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.22.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.22.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.22.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.22.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.22.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.22.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.22.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.23.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.23.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.23.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.23.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.23.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.23.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.23.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.23.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.23.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.23.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.24.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.24.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.24.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.24.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.24.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.24.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.24.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.24.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.24.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.24.lxu_cache_weights", "sparse_arch.embedding_bag_collection.embedding_bags.25.D_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.25.rows_per_table", "sparse_arch.embedding_bag_collection.embedding_bags.25.bounds_check_warning", "sparse_arch.embedding_bag_collection.embedding_bags.25.weights_tys", "sparse_arch.embedding_bag_collection.embedding_bags.25.index_remappings_array_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.25.index_remappings_array", "sparse_arch.embedding_bag_collection.embedding_bags.25.index_remapping_hash_table_offsets", "sparse_arch.embedding_bag_collection.embedding_bags.25.index_remapping_hash_table", "sparse_arch.embedding_bag_collection.embedding_bags.25.table_wise_cache_miss", "sparse_arch.embedding_bag_collection.embedding_bags.25.lxu_cache_weights".
        Unexpected key(s) in state_dict: "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_0.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_1.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_2.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_3.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_4.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_5.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_6.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_7.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_8.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_9.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_10.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_11.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_12.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_13.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_14.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_15.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_16.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_17.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_18.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_19.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_20.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_21.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_22.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_23.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_24.weight", "sparse_arch.embedding_bag_collection.embedding_bags.t_cat_25.weight".
```

Am I expecting the wrong behavior?

**Comment by YLGH** [comment]
Fixed in https://github.com/pytorch/torchrec/pull/547
