### ISSUE TITLE
Error when importing `torchrec`

### ISSUE THREAD

**Issue by xquyvu** [meta-pytorch/torchrec#671]
I got this error when trying to run `import torchrec`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/torchrec/__init__.py", line 8, in <module>
    import torchrec.distributed  # noqa
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/__init__.py", line 8, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/model_parallel.py", line 17, in <module>
    from torchrec.distributed.embeddingbag import (
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/embeddingbag.py", line 28, in <module>
    from torchrec.distributed.cw_sharding import CwEmbeddingSharding
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/torchrec/distributed/cw_sharding.py", line 12, in <module>
    from fbgemm_gpu.permute_pooled_embedding_modules import PermutePooledEmbeddings
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/fbgemm_gpu/__init__.py", line 12, in <module>
    torch.ops.load_library(os.path.join(os.path.dirname(__file__), "fbgemm_gpu_py.so"))
  File "/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so, 0x0006): tried: '/Users/quyvu/.pyenv/versions/3.9.13/envs/torchrec/lib/python3.9/site-packages/fbgemm_gpu/fbgemm_gpu_py.so' (not a mach-o file)
```

I'm using an Intel MacBook with an AMD GPU.

Environment:
MacOS Monterey 12.6
Python version: `3.9.14`

```
arrow==1.2.3
attrs==22.1.0
certifi==2022.9.24
charset-normalizer==2.1.1
cmake==3.24.1.1
Cython==0.29.32
distro==1.7.0
docker==6.0.0
docstring-parser==0.8.1
exceptiongroup==1.0.0rc9
filelock==3.8.0
fsspec==2022.8.2
hypothesis==6.54.6
idna==3.4
iopath==0.1.10
Jinja2==3.1.2
MarkupSafe==2.1.1
mypy-extensions==0.4.3
ninja==1.10.2.4
numpy==1.23.3
packaging==21.3
pandas==1.5.0
portalocker==2.5.1
pyarrow==9.0.0
pyDeprecate==0.3.2
pyparsing==3.0.9
pyre-extensions==0.0.29
python-dateutil==2.8.2
pytz==2022.2.1
PyYAML==6.0
requests==2.28.1
scikit-build==0.15.0
six==1.16.0
sortedcontainers==2.4.0
tabulate==0.8.10
torch==1.12.1
torchmetrics==0.9.3
torchrec==0.1.0
torchx-nightly==2022.9.28
tqdm==4.64.1
typing==3.7.4.3
typing-inspect==0.8.0
typing_extensions==4.3.0
urllib3==1.26.12
websocket-client==1.4.1
```

Any comments would be greatly appreciated.

Thanks.

**Comment by YLGH** [comment]
> I'm using an Intel MacBook with an AMD GPU.

We current don't support Macbook w/ AMD GPU, this is something in the works though. Sorry for the inconvenience :(
