### ISSUE TITLE
fuse_embedding_optimizer causes inconsistencies between distributed model with world_size=2 and non distributed model

### ISSUE THREAD

**Issue by jiannanWang** [meta-pytorch/torchrec#766]
Hi,

I was training a model using `fuse_embedding_optimize` to fuse the embedding bags with `RowWiseAdagrad` optimizer, but found inconsistencies between the distributed model with world_size=2 and non distributed model.

I first created a test model with 
- one sparse part containing:
  - one EmbeddingBagCollection containing one embedding bag, 
  - one weighted EmbeddingBagCollection containing one embedding bag, 
- one dense part containing a linear layer
- one over part containing a linear layer.

Then I generate input to that model using `ModelInput.generate`, while `ModelInput` is in `torchrec.distributed.test_utils.test_model`.

Then I call `fuse_embedding_optimizer` to fuse the model with RowWiseAdagrad and {"lr": 0.1}. 

After that, I train the model on the input and check the model's outputs.

I compared the model trained in distributed setting with world_size=2 and the model trained in non-distributed setting. The model's results are different, and `torch.testing.assert_close(global_pred, torch.cat(all_local_pred))` will raise an AssertionError. While the model's results are expected to be the same.

As I further tested, if I don't use `fuse_embedding_optimizer`, or use `apply_overlapped_optimizer` instead, or change world_size from 2 to 1, or test inference instead of training, the model's results will be the same and the assertion will not raise.

I feel there might be a bug in `fuse_embedding_optimizer`, or I am using it wrong. Can you please help me confirm if it is a bug? Thanks!

I copied the reproduction code below. I was testing using torchrec 0.2.0.

```
import copy
import os
import torch
import torchrec
from torchrec.optim.rowwise_adagrad import RowWiseAdagrad
from torchrec.sparse.jagged_tensor import KeyedTensor
from torchrec.optim.keyed import CombinedOptimizer, KeyedOptimizerWrapper
from torchrec.modules.embedding_configs import EmbeddingBagConfig
from torchrec.modules.embedding_modules import EmbeddingBagCollection
from torchrec.modules.fused_embedding_modules import fuse_embedding_optimizer
from torchrec.distributed.test_utils.test_sharding import copy_state_dict
from typing import Dict
import torch.nn as nn
from torchrec.distributed.test_utils.test_model import ModelInput

class TestModel(nn.Module):
    def __init__(
        self,
        dense_device=torch.device("cpu"),
        sparse_device=torch.device("cpu"),
    ):
        super().__init__()
        self.in_features = 10
        self.out_features = 1

        self.dense_device = dense_device
        self.sparse_device = sparse_device

        self.dense = nn.Linear(
            in_features=self.in_features, out_features=self.out_features, device=self.dense_device
        )
        self.tables = [
            EmbeddingBagConfig(
                num_embeddings=10,
                embedding_dim=4,
                name="table_" + str(0),
                feature_names=["feature_" + str(0)],
            )
        ]
        self.sparse = EmbeddingBagCollection(
            tables=self.tables,
            device=self.sparse_device,
        )

        self.weighted_tables = [
            EmbeddingBagConfig(
                num_embeddings=10,
                embedding_dim=4,
                name="weighted_table_" + str(0),
                feature_names=["weighted_feature_" + str(0)],
            )
        ]
        self.sparse_weighted = EmbeddingBagCollection(
            tables=self.weighted_tables,
            is_weighted=True,
            device=self.sparse_device
        )

        in_features_concat = (
            self.out_features
            + sum(
                [
                    table.embedding_dim * len(table.feature_names)
                    for table in self.tables
                ]
            )
            + sum(
                [
                    table.embedding_dim * len(table.feature_names)
                    for table in self.weighted_tables
                ]
            )
        )

        self.over = nn.Linear(
            in_features=in_features_concat, out_features=self.out_features, device=self.dense_device
        )

    def forward(
        self,
        input,
    ):
        dense_r = self.dense(input.float_features)
        sparse_r = self.sparse(input.idlist_features)
        sparse_weighted_r = self.sparse_weighted(input.idscore_features)
        result = KeyedTensor(
            keys=sparse_r.keys() + sparse_weighted_r.keys(),
            length_per_key=sparse_r.length_per_key()
            + sparse_weighted_r.length_per_key(),
            values=torch.cat([sparse_r.values(), sparse_weighted_r.values()], dim=1),
        )

        _features = [
            feature for table in self.tables for feature in table.feature_names
        ]
        _weighted_features = [
            feature for table in self.weighted_tables for feature in table.feature_names
        ]

        ret_list = []
        ret_list.append(dense_r)
        for feature_name in _features:
            ret_list.append(result[feature_name])
        for feature_name in _weighted_features:
            ret_list.append(result[feature_name])
        ret_concat = torch.cat(ret_list, dim=1)

        over_r = self.over(ret_concat)
        pred = torch.sigmoid(torch.mean(over_r, dim=1))
        if self.training:
            return (
                torch.nn.functional.binary_cross_entropy_with_logits(pred, input.label),
                pred,
            )
        else:
            return pred

def generate_inputs(
    world_size: int,
    tables,
    weighted_tables = None,
    batch_size = 4,
    num_float_features = 16,
):
    return ModelInput.generate(
        batch_size=batch_size,
        world_size=world_size,
        num_float_features=num_float_features,
        tables=tables,
        weighted_tables=weighted_tables or [],
    )

def single_rank_execution(
    rank: int,
    world_size: int,
    model: torch.nn.Module,
    inputs,
    backend: str,
) -> None:
    import os
    import torch
    import torch.distributed as dist
    from torchrec.distributed.embeddingbag import EmbeddingBagCollectionSharder
    from torchrec.distributed.model_parallel import DistributedModelParallel
    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
    from torchrec.distributed.types import ModuleSharder, ShardingEnv
    from torchrec.optim import RowWiseAdagrad
    from typing import cast

    def init_distributed_single_host(
        rank: int,
        world_size: int,
        backend: str,
        # pyre-fixme[11]: Annotation `ProcessGroup` is not defined as a type.
    ) -> dist.ProcessGroup:
        os.environ["RANK"] = f"{rank}"
        os.environ["WORLD_SIZE"] = f"{world_size}"
        dist.init_process_group(rank=rank, world_size=world_size, backend=backend)
        return dist.group.WORLD

    if backend == "nccl":
        device = torch.device(f"cuda:{rank}")
        torch.cuda.set_device(device)
    else:
        device = torch.device("cpu")
    model = model.to(device)

    global_model = copy.deepcopy(model)

    global_model = global_model.to(device)
    global_input = inputs[0][0].to(device)

    local_model = copy.deepcopy(model).to(device)

    topology = Topology(world_size=world_size, compute_device="cpu")
    pg = init_distributed_single_host(rank, world_size, backend)
    planner = EmbeddingShardingPlanner(
        topology=topology,
    )
    sharders = [cast(ModuleSharder[torch.nn.Module], EmbeddingBagCollectionSharder())]
    plan = planner.collective_plan(model, sharders, pg)

    local_model = DistributedModelParallel(
        model,
        env=ShardingEnv.from_process_group(pg),
        plan=plan,
        sharders=sharders,
        device=device,
    )

    copy_state_dict(local_model.state_dict(), global_model.state_dict())

    dense_optim = torch.optim.SGD
    dense_optim_params = {"lr": 0.1}

    local_optim_dense = KeyedOptimizerWrapper(
        dict(local_model.named_parameters()),
        lambda params: dense_optim(params, **dense_optim_params),
    )
    local_opt = CombinedOptimizer([local_model.fused_optimizer, local_optim_dense])

    local_input = inputs[0][1][rank].to(device)
    local_pred = gen_full_pred_after_one_step(local_model, local_opt, local_input)
    all_local_pred = []
    for _ in range(world_size):
        all_local_pred.append(torch.empty_like(local_pred))
    dist.all_gather(all_local_pred, local_pred, group=pg)

    global_opt = dense_optim(global_model.parameters(), **dense_optim_params)
        
    global_pred = gen_full_pred_after_one_step(global_model, global_opt, global_input)

    torch.testing.assert_close(global_pred, torch.cat(all_local_pred))
    return
  
def gen_full_pred_after_one_step(
    model,
    opt,
    input,
) -> torch.Tensor:
    # Run a single training step of the global model.
    opt.zero_grad()
    model.train(True)
    loss, _ = model(input)
    loss.backward()
    opt.step()

    # Run a forward pass of the global model.
    with torch.no_grad():
        model.train(False)
        full_pred = model(input)
        return full_pred

import multiprocess
   
def spmd_sharing_simulation(
    model,
    input,
    world_size = 2,
):
    ctx = multiprocess.get_context("spawn")
    processes = []
    for rank in range(world_size):
        p = ctx.Process(
            target=single_rank_execution,
            args=(
                rank,
                world_size,
                model,
                input,
                "gloo"
            ),
        )
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
        assert 0 == p.exitcode

if __name__ == "__main__":
    os.environ["MASTER_ADDR"] = "localhost"
    os.environ["MASTER_PORT"] = "29500"

    world_size = 2
    model = TestModel()
    print(model)
    inputs = [
        generate_inputs(
            world_size=world_size,
            tables=model.tables,
            weighted_tables=model.weighted_tables,
            num_float_features=model.in_features,
        )
    ]
    print(inputs)

    model = fuse_embedding_optimizer(
        model,
        optimizer_type=RowWiseAdagrad,
        optimizer_kwargs={"lr": 0.1},
        device=torch.device("cpu"),
    )

    spmd_sharing_simulation(model, inputs, world_size)

```

**Comment by YLGH** [comment]
hey Jiannan, thanks for reporting,

could you help check to see that the ShardedModule has something called ShardedFusedEmbeddingBagCollection?

I'm seeing:

sharders = [cast(ModuleSharder[torch.nn.Module], EmbeddingBagCollectionSharder())]

so it likely doesn't replace the fused_embedding_bag_collection with ShardedFusedEmbeddingBagCollection. Since it's a fused kernel, the gradients won't be synced

**Comment by jiannanWang** [comment]
Thank you for your response!

I copied the sharedmodule below and it doesn't have the ShardedFusedEmbeddingBagCollection.
```
DistributedModelParallel(
  (_dmp_wrapped_module): DistributedDataParallel(
    (module): TestModel(
      (dense): Linear(in_features=10, out_features=1, bias=True)
      (sparse): FusedEmeddingBagCollection(
        (_emb_modules): ModuleList(
          (0): _BatchedFusedEmbeddingBag(
            (_emb_module): SplitTableBatchedEmbeddingBagsCodegen()
          )
        )
      )
      (sparse_weighted): FusedEmeddingBagCollection(
        (_emb_modules): ModuleList(
          (0): _BatchedFusedEmbeddingBag(
            (_emb_module): SplitTableBatchedEmbeddingBagsCodegen()
          )
        )
      )
      (over): Linear(in_features=9, out_features=1, bias=True)
    )
  )
)
```
As I understand, the problem is I use a wrong sharder. So I changed the sharder from EmbeddingBagCollectionSharder to FusedEmbeddingBagCollectionSharder. But then I encounter a different error:
```
Traceback (most recent call last):
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/e/Projects/torchrec-private/eagle_plus_tests/repro_bug.py", line 191, in single_rank_execution
    device=device,
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/model_parallel.py", line 249, in __init__
    fused_optims=fused_optims,
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/model_parallel.py", line 342, in _init_dmp
    fused_optims,
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/model_parallel.py", line 375, in _shard_modules_impl
    fused_optims,
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/model_parallel.py", line 358, in _shard_modules_impl
    self.device,
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/fused_embeddingbag.py", line 101, in shard
    return ShardedFusedEmbeddingBagCollection(module, params, env, device)
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/fused_embeddingbag.py", line 70, in __init__
    static_graph=True,
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 580, in __init__
    {p.device for p in module.parameters()},
  File "/home/jiannan/anaconda3/envs/tr02/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 677, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [device(type='cpu')], output_device None, and module parameters {device(type='cpu')}.
```
If I comment out the fuse_embedding_optimizer function, the error disappears. 
What is this error for? And what is the correct way to train a model with FusedEmbeddingBagCollection?

**Comment by YLGH** [comment]
Ah, we need to leave a comment, but current DATA_PARALLEL sharding isn't fully supported for FusedEmbeddingBagCollection.

Could you try setting the sharding type to be TABLE_WISE or ROW_WISE?

**Comment by jiannanWang** [comment]
Thank you very much for your help! Since my original issue is solved, I would like to close this issue.
