### ISSUE TITLE
Install torch rec on google cloud vertex ai notebook is not working.  

### ISSUE THREAD

**Issue by zzhao2-sc** [meta-pytorch/torchrec#886]
HI team, 
I setup environment on gcp 

```
I install torchrec via:
conda create -n py37 python=3.7
conda activate py37
conda install pytorch pytorch-cuda=11.6 -c pytorch-nightly -c nvidia -y
pip install -r requirements.txt
cd torchrec/ 
python setup.py install develop
```

I met error: 

```
(py37) zzhao2@zihanzhao-large-dev:~/code/torchrec$ torchx run -s local_cwd dist.ddp -j 1x2 --gpu 2 --script test_installation.py
torchx 2022-12-10 02:43:51 INFO     Log directory not set in scheduler cfg. Creating a temporary log dir that will be deleted on exit. To preserve log directory set the `log_dir` cfg option
torchx 2022-12-10 02:43:51 INFO     Log directory is: /tmp/torchx_u_y9m5bi
local_cwd://torchx/test_installation-mwhd4nznnjs7f
torchx 2022-12-10 02:43:51 INFO     Waiting for the app to finish...
test_installation/0 Traceback (most recent call last):
test_installation/0   File "/opt/conda/envs/py37/lib/python3.7/runpy.py", line 183, in _run_module_as_main
test_installation/0     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
test_installation/0   File "/opt/conda/envs/py37/lib/python3.7/runpy.py", line 109, in _get_module_details
test_installation/0     __import__(pkg_name)
test_installation/0   File "/opt/conda/envs/py37/lib/python3.7/site-packages/torch/__init__.py", line 219, in <module>
test_installation/0     from torch._C import *  # noqa: F403
test_installation/0 ImportError: /opt/conda/envs/py37/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so: symbol cusparseSpSM_analysis version libcusparse.so.11 not defined in file libcusparse.so.11 with link time reference
torchx 2022-12-10 02:43:52 INFO     Job finished: 5
torchx 2022-12-10 02:43:52 ERROR    AppStatus:
  msg: <NONE>
  num_restarts: 0
  roles: []
  state: FAILED (5)
  structured_error_msg: <NONE>
  ui_url: file:///tmp/torchx_u_y9m5bi/torchx/test_installation-mwhd4nznnjs7f
```
Here is my cuda info

```
(py37) @-large-dev:~/code/torchrec$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```
Any ideas?

**Comment by colin2328** [comment]
I would guess that something is wrong with your fbgemm install or environment

try running the benchmarks of fbgemm: https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu#usage-example
even try:
```
import torch
import fbgemm_gpu
torch.ops.fbgemm.jagged_to_padded_dense
```
If those fail, please make an issue on fbgemm https://github.com/pytorch/FBGEMM/issues

**Comment by zzhao2-sc** [comment]
Hi @colin2328, is that possible it is related to CUDA version? 

> Currently tested with CUDA 11.3, 11.5, 11.6, and 11.7 in CI. In all cases, we test with PyTorch packages which are built with CUDA 11.7.

But for GCS notebook, it only support CUDA 11.0 
![Screen Shot 2022-12-12 at 11 05 40 AM](https://user-images.githubusercontent.com/112680110/207132410-e2b43088-30ba-419b-80a1-3b7cb1c59e86.png)

**Comment by colin2328** [comment]
for older CUDA versions, you will need to install from source with the approprirate CUDA_ARCH_LIST https://github.com/pytorch/FBGEMM/tree/main/fbgemm_gpu#build-from-source

**Comment by colin2328** [comment]
@zzh1024  were you able to geet anything working?
