### ISSUE TITLE
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by jiannanWang** [meta-pytorch/torchrec#995]
I met the above error message when I was trying to apply `quantize_embeddings()` and `QuantEmbeddingBagCollectionSharder()` to a model using `"gloo"` backend. I'm not sure if this is a bug or not. I report the bug here since I was asked to. I copied a reproduction code snippet and the output traceback below.

I was using pytorch 1.12.0, torchrec 0.2.0, and fbgemm-gpu 0.2.0.

Reproduction Code
```
import os

import torch
import torch.distributed as dist
import torch.nn as nn
import torchrec.distributed as trec_dist
from torchrec.distributed.embeddingbag import EmbeddingBagSharder
from torchrec.distributed.model_parallel import DistributedModelParallel
from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
from torchrec.distributed.test_utils.test_model import ModelInput
from torchrec.distributed.types import ShardingEnv
from torchrec.modules.embedding_configs import EmbeddingBagConfig
from torchrec.modules.embedding_modules import EmbeddingBagCollection

def setup():
    os.environ["RANK"] = "0"
    os.environ["WORLD_SIZE"] = "1"
    os.environ["LOCAL_WORLD_SIZE"] = "1"
    os.environ["MASTER_ADDR"] = str("localhost")
    os.environ["MASTER_PORT"] = str("12345")
    os.environ["NCCL_SOCKET_IFNAME"] = "lo"

    device = torch.device("cpu")
    backend = "gloo"
    try:
        dist.init_process_group(backend=backend)
    except:
        pass
    return device


device = setup()

class TestModel(nn.Module):
    def __init__(self):
        super().__init__()

        table_params = [
            [776, 908],
            [430, 40],
        ]

        self.tables = [
            EmbeddingBagConfig(
                num_embeddings=table_params[i][0],
                embedding_dim=table_params[i][1],
                name="table_" + str(i),
                feature_names=["feature_" + str(i)],
            )
            for i in range(len(table_params))
        ]

        self.sparse = EmbeddingBagCollection(
            tables=self.tables,
            is_weighted=False,
        )

    def forward(
        self,
        input: ModelInput,
    ):
        sparse_r = self.sparse(input.idlist_features)
        return sparse_r

def shard_model(device):
    model = TestModel()

    input = ModelInput.generate(
        batch_size=10,
        world_size=1,
        num_float_features=1,
        tables=model.tables,
        weighted_tables=[],
    )
    
    from torchrec.inference.modules import quantize_embeddings
    model = quantize_embeddings(model, dtype=torch.qint8, inplace=True)
    model.to(device)

    pg = dist.GroupMember.WORLD
    assert pg is not None, "Process group is not initialized"
    env = ShardingEnv.from_process_group(pg)

    planner = EmbeddingShardingPlanner(
        topology=Topology(
            local_world_size=trec_dist.comm.get_local_size(env.world_size),
            world_size=env.world_size,
            compute_device=device.type,
        ),
    )

    from torchrec.distributed.quant_embeddingbag import QuantEmbeddingBagCollectionSharder
    sharders = [QuantEmbeddingBagCollectionSharder()]
    plan = planner.collective_plan(model, sharders, pg)
    print(device)
    dmp = DistributedModelParallel(
        module=model,
        init_data_parallel=False,
        device=device,
        sharders=sharders,
        plan=plan,
    )

    return dmp(input[0])


shard_model(device)
```

Traceback
```
Traceback (most recent call last):
  File "others/reproduce_quant_gloo.py", line 106, in <module>
    shard_model(device)
  File "others/reproduce_quant_gloo.py", line 103, in shard_model
    return dmp(input[0])
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/model_parallel.py", line 276, in forward
    return self._dmp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "others/reproduce_quant_gloo.py", line 61, in forward
    sparse_r = self.sparse(input.idlist_features)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/types.py", line 433, in forward
    return self.compute_and_output_dist(ctx, dist_input)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/quant_embeddingbag.py", line 215, in compute_and_output_dist
    input,
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/quant_embeddingbag.py", line 212, in <listcomp>
    for lookup, dist, features in zip(
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/sharding/tw_sharding.py", line 428, in forward
    return self._dist.forward(local_embs)
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torchrec/distributed/dist_data.py", line 758, in forward
    self._cat_dim,
  File "/opt/conda/envs/tr02/lib/python3.7/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/home/ec2-user/miniconda/envs/build_binary/lib/python3.7/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":24, please report a bug to PyTorch.
```

**Comment by YLGH** [comment]
Hey @jiannanWang - thanks for reporting. Could check if using fbgemm-gpu-cpu works? You'd need to pip uninstall fbgemm-gpu first, and then pip install fbgemm-gpu-cpu. My hunch is that fbgemm-gpu always places some things on cuda devices

**Comment by jiannanWang** [comment]
Hi, thank you for your reply! I tried to uninstall fbgemm-gpu 0.2.0 and then install fbgemm-gpu-cpu 0.2.0, and I got the error message below.

One thing I'm curious about is since I was using gloo backend, I was under the assumption that I'm using CPU instead of GPU. Why does this error message mention running with CUDA backend? Does the quantization only work with CUDA backend?

```
Traceback (most recent call last):
  File "reproduce_quant_gloo.py", line 106, in <module>
    shard_model(device)
  File "reproduce_quant_gloo.py", line 103, in shard_model
    return dmp(input[0])
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/model_parallel.py", line 276, in forward
    return self._dmp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "reproduce_quant_gloo.py", line 61, in forward
    sparse_r = self.sparse(input.idlist_features)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/types.py", line 433, in forward
    return self.compute_and_output_dist(ctx, dist_input)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/quant_embeddingbag.py", line 215, in compute_and_output_dist
    input,
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/quant_embeddingbag.py", line 212, in <listcomp>
    for lookup, dist, features in zip(
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/embedding_lookup.py", line 663, in forward
    embeddings.append(embedding_lookup(sparse_features_rank))
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/embedding_lookup.py", line 574, in forward
    embeddings.append(emb_op(features))
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/distributed/quant_embedding_kernel.py", line 162, in forward
    offsets=features.offsets().int(),
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/sparse/jagged_tensor.py", line 825, in offsets
    _offsets = _maybe_compute_offsets(self._lengths, self._offsets)
  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/sparse/jagged_tensor.py", line 65, in _maybe_compute_offsets
    offsets = _to_offsets(lengths)  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torchrec/sparse/jagged_tensor.py", line 36, in _to_offsets    return torch.ops.fbgemm.asynchronous_complete_cumsum(lengths)  File "/opt/conda/envs/tr02cpu/lib/python3.7/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
NotImplementedError: Could not run 'fbgemm::asynchronous_complete_cumsum' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'fbgemm::asynchronous_complete_cumsum' is only available for these backends: [Dense, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].

CPU: registered at /home/ec2-user/actions-runner/_work/FBGEMM/FBGEMM/fbgemm_gpu/src/sparse_ops_cpu.cpp:2435 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/PythonFallbackKernel.cpp:133 [backend fallback]
Named: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
AutogradXLA: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:51 [backend fallback]
AutogradMPS: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:59 [backend fallback]
AutogradXPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
AutogradHPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:68 [backend fallback]
AutogradLazy: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/VariableFallbackKernel.cpp:55 [backend fallback]
Tracer: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/torch/csrc/autograd/TraceTypeManual.cpp:295 [backend fallback]
AutocastCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/autocast_mode.cpp:481 [backend fallback]
Autocast: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/autocast_mode.cpp:324 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/BatchingRegistrations.cpp:1064 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
Functionalize: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/FunctionalizeFallbackKernel.cpp:89 [backend fallback]
PythonTLSSnapshot: registered at /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/core/PythonFallbackKernel.cpp:137 [backend fallback]
```

**Comment by awsankur** [comment]
Any updates on the above issue? I get the same error.

**Comment by jiannanWang** [comment]
Hi, hope you're doing well! Seems like others are meeting the same issues as well. I just want to check if there're any updates on this issue. Thanks!
